
//--------------------------------------------------------
// ORBt610Model
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

#import "ORBt610Model.h"
#import "ORSerialPortAdditions.h"
#import "ORDataTypeAssigner.h"
#import "ORDataPacket.h"
#import "ORTimeRate.h"
#import "ORAlarm.h"

//Gated logging: per request, log ONLY when verbose is OFF (verbose ON = quiet).
//Usable inside instance methods (references the 'verbose' ivar and 'self').
#define BTVLOG(...) do{ if(!verbose) NSLog(__VA_ARGS__); }while(0)

#pragma mark ***External Strings
NSString* ORBt610ModelDumpCountChanged		    = @"ORBt610ModelDumpCountChanged";
NSString* ORBt610ModelDumpInProgressChanged     = @"ORBt610ModelDumpInProgressChanged";
NSString* ORBt610ModelIsLogChanged			    = @"ORBt610ModelIsLogChanged";
NSString* ORBt610ModelVerboseChanged		    = @"ORBt610ModelVerboseChanged";
NSString* ORBt610ModelHoldTimeChanged		    = @"ORBt610ModelHoldTimeChanged";
NSString* ORBt610ModelPollTimeChanged            = @"ORBt610ModelPollTimeChanged";
NSString* ORBt610ModelTempUnitsChanged		    = @"ORBt610ModelTempUnitsChanged";
NSString* ORBt610ModelCountUnitsChanged	        = @"ORBt610ModelCountUnitsChanged";
NSString* ORBt610ModelStatusBitsChanged	        = @"ORBt610ModelStatusBitsChanged";
NSString* ORBt610ModelLocationChanged		    = @"ORBt610ModelLocationChanged";
NSString* ORBt610ModelHumidityChanged		    = @"ORBt610ModelHumidityChanged";
NSString* ORBt610ModelTemperatureChanged	    = @"ORBt610ModelTemperatureChanged";
NSString* ORBt610ModelActualDurationChanged     = @"ORBt610ModelActualDurationChanged";
NSString* ORBt610ModelCountAlarmLimitChanged    = @"ORBt610ModelCountAlarmLimitChanged";
NSString* ORBt610ModelMaxCountsChanged		    = @"ORBt610ModelMaxCountsChanged";
NSString* ORBt610ModelCycleNumberChanged	    = @"ORBt610ModelCycleNumberChanged";
NSString* ORBt610ModelCycleStartedChanged	    = @"ORBt610ModelCycleStartedChanged";
NSString* ORBt610ModelRunningChanged		    = @"ORBt610ModelRunningChanged";
NSString* ORBt610ModelCycleDurationChanged      = @"ORBt610ModelCycleDurationChanged";
NSString* ORBt610ModelNumSamplesChanged	        = @"ORBt610ModelNumberSamplesChanged";
NSString* ORBt610ModelCountChanged			    = @"ORBt610ModelCount2Changed";
NSString* ORBt610ModelMissedCountChanged        = @"ORBt610ModelMissedCountChanged";
NSString* ORBt610ModelOpTimerChanged            = @"ORBt610ModelOpTimerChanged";
NSString* ORBt610ModelMeasurementDateChanged    = @"ORBt610ModelMeasurementDateChanged";
NSString* ORBt610ModelSerialNumberChanged       = @"ORBt610ModelSerialNumberChanged";
NSString* ORBt610ModelSoftwareVersionChanged    = @"ORBt610ModelSoftwareVersionChanged";
NSString* ORBt610ModelChannelSizesChanged       = @"ORBt610ModelChannelSizesChanged";

NSString* ORBt610Lock = @"ORBt610Lock";

@interface ORBt610Model (private)
- (void) addCmdToQueue:(NSString*)aCmd;
- (void) process_response:(NSString*)theResponse;
- (void) checkCycle;
- (void) cancelCycleCheck;

- (void) dumpTimeout;
- (void) clearDelay;
- (void) processOneCommandFromQueue;
- (void) startDataArrivalTimeout;
- (void) cancelDataArrivalTimeout;
- (void) doCycleKick;
- (void) postCouchDBRecord;
@end

@implementation ORBt610Model

- (id) init
{
	self = [super init];
	[[self undoManager] disableUndoRegistration];
	int i;
	for(i=0;i<6;i++){
		[self setIndex:i maxCounts:1000];
		[self setIndex:i countAlarmLimit:800];
	}
	[[self undoManager] enableUndoRegistration];
	return self;
}

- (void) dealloc
{
    [cycleStarted release];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [NSObject cancelPreviousPerformRequestsWithTarget:self];
    [buffer release];
    [opTimer release];
    [measurementDate release];
    [serialNumber release];
    [softwareVersion release];
    {int ci; for(ci=0;ci<6;ci++) [channelSize[ci] release];}

	int i;
	for(i=0;i<8;i++){
		[timeRates[i] release];
	}	
	
	[sensorErrorAlarm release];
	[sensorErrorAlarm clearAlarm];

	[lowBatteryAlarm release];
	[lowBatteryAlarm clearAlarm];

	[countSize1Alarm release];
	[countSize1Alarm clearAlarm];
  
    [countSize2Alarm release];
    [countSize2Alarm clearAlarm];
 
    
	[missingCyclesAlarm release];
	[missingCyclesAlarm clearAlarm];

	[super dealloc];
}

- (void) sleep
{
	[NSObject cancelPreviousPerformRequestsWithTarget:self];
	[super sleep];
}

- (void) wakeUp
{
	[super wakeUp];
	//resume the heartbeat (sleep cancels all scheduled perform requests)
	if([serialPort isOpen]) [self pollDevice];
}

- (void) setUpImage
{
	[self setImage:[NSImage imageNamed:@"Bt610.tif"]];
}

- (void) makeMainController
{
	[self linkToController:@"ORBt610Controller"];
}
- (NSString*) helpURL
{
	return @"RS232/Bt610.html";
}

- (void) dataReceived:(NSNotification*)note
{
    if([[note userInfo] objectForKey:@"serialPort"] == serialPort){
		
        NSString* theString = [[[[NSString alloc] initWithData:[[note userInfo] objectForKey:@"data"] 
												      encoding:NSASCIIStringEncoding] autorelease] uppercaseString];
	
		
        //the serial port may break the data up into small chunks, so we have to accumulate the chunks until
		//we get a full piece.
				
        if(!buffer)buffer = [[NSMutableString string] retain];
        [buffer appendString:theString];	
		
        do {
            NSRange lineRange = [buffer rangeOfString:@"\r\n"];
            if(lineRange.location!= NSNotFound){
                NSString* theResponse = [[[buffer substringToIndex:lineRange.location+1] copy] autorelease];
                [buffer deleteCharactersInRange:NSMakeRange(0,lineRange.location+1)];      //take the cmd out of the buffer
				
				if([theResponse length] != 0){
					[self process_response:theResponse];
				}
				if(!dumpInProgress){
					[self setLastRequest:nil];			 //clear the last request
					[self processOneCommandFromQueue];	 //do the next command in the queue
				}

            }
        } while([buffer rangeOfString:@"\r\n"].location!= NSNotFound);
	}
}

#pragma mark ***Accessors
- (int) missedCycleCount
{
    return missedCycleCount;
}

- (void) setMissedCycleCount:(int)aValue
{
    missedCycleCount = aValue;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelMissedCountChanged object:self];
    
	if(((missedCycleCount >= 3) && (numSamples==0)) ||
       ((missedCycleCount > 0) && (numSamples>0))){
		if(!missingCyclesAlarm){
			NSString* s = [NSString stringWithFormat:@"Bt610 (Unit %u) Missing Cycles",[self uniqueIdNumber]];
			missingCyclesAlarm = [[ORAlarm alloc] initWithName:s severity:kHardwareAlarm];
			[missingCyclesAlarm setSticky:YES];
            if(numSamples>0)[missingCyclesAlarm setHelpString:@"The particle counter did not report counts at the end of its last cycle.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
            else [missingCyclesAlarm setHelpString:@"The particle counter is not reporting counts at the end of its cycle. ORCA tried to kick start it at least three times.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
			[missingCyclesAlarm postAlarm];
		}
	}
	else {
		[missingCyclesAlarm clearAlarm];
		[missingCyclesAlarm release];
		missingCyclesAlarm = nil;
	}
}

- (int) dumpCount
{
    return dumpCount;
}

- (void) setDumpCount:(int)aDumpCount
{
    dumpCount = aDumpCount;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelDumpCountChanged object:self];
}

- (BOOL) dumpInProgress
{
    return dumpInProgress;
}

- (void) setDumpInProgress:(BOOL)aDumpInProgress
{
    dumpInProgress = aDumpInProgress;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelDumpInProgressChanged object:self];
}

- (BOOL) isLog
{
    return isLog;
}

- (void) setIsLog:(BOOL)aIsLog
{
    [[[self undoManager] prepareWithInvocationTarget:self] setIsLog:isLog];
    isLog = aIsLog;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelIsLogChanged object:self];
}

- (BOOL) verbose
{
    return verbose;
}

- (void) setVerbose:(BOOL)aVerbose
{
    [[[self undoManager] prepareWithInvocationTarget:self] setVerbose:verbose];
    verbose = aVerbose;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelVerboseChanged object:self];
}

- (int) holdTime
{
    return holdTime;
}

- (int) pollTime
{
    return pollTime;
}

- (void) setHoldTime:(int)aHoldTime
{
	if(aHoldTime<0)aHoldTime = 0;
	if(aHoldTime>9999)aHoldTime = 9999;
    [[[self undoManager] prepareWithInvocationTarget:self] setHoldTime:holdTime];
    holdTime = aHoldTime;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelHoldTimeChanged object:self];
}

- (void) setPollTime:(int)aPollTime
{
    if(aPollTime<0)aPollTime = 0;
    if(aPollTime>9999)aPollTime = 9999;
    [[[self undoManager] prepareWithInvocationTarget:self] setPollTime:pollTime];
    pollTime = aPollTime;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelPollTimeChanged object:self];
}
- (void) setOpTimer:(NSString*)aValue
{
    [opTimer release];
    opTimer = nil;
    opTimer = [aValue copy];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelOpTimerChanged object:self];
}

- (NSString*) opTimer
{
    if(opTimer)return opTimer;
    else return @"";
}

- (int) tempUnits
{
    return tempUnits;
}

- (void) setTempUnits:(int)aTempUnits
{
	if(aTempUnits<0)aTempUnits = 0;
	if(aTempUnits>1)aTempUnits = 1;
    [[[self undoManager] prepareWithInvocationTarget:self] setTempUnits:tempUnits];
    tempUnits = aTempUnits;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelTempUnitsChanged object:self];
}

- (int) countUnits
{
    return countUnits;
}

- (void) setCountUnits:(int)aCountUnits
{
    [[[self undoManager] prepareWithInvocationTarget:self] setCountUnits:countUnits];
    countUnits = aCountUnits;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCountUnitsChanged object:self];
}

- (int) statusBits
{
    return statusBits;
}

- (void) setStatusBits:(int)aStatusBits
{
    statusBits = aStatusBits;
	[self checkAlarms];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelStatusBitsChanged object:self];
}

- (void) checkAlarms
{
	if(statusBits & 0x10){
		if(!lowBatteryAlarm){
			NSString* s = [NSString stringWithFormat:@"Bt610 (Unit %u)",[self uniqueIdNumber]];
			lowBatteryAlarm = [[ORAlarm alloc] initWithName:s severity:kHardwareAlarm];
			[lowBatteryAlarm setSticky:YES];
			[lowBatteryAlarm setHelpString:@"The battery on the particle counter is low. Is it supposed to be running on the battery?\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
			[lowBatteryAlarm postAlarm];
		}
	}
	else {
		[lowBatteryAlarm clearAlarm];
		[lowBatteryAlarm release];
		lowBatteryAlarm = nil;
	}
	
	if(statusBits & 0x20){
		if(!sensorErrorAlarm){
			NSString* s = [NSString stringWithFormat:@"Bt610 (Unit %u)",[self uniqueIdNumber]];
			sensorErrorAlarm = [[ORAlarm alloc] initWithName:s severity:kHardwareAlarm];
			[sensorErrorAlarm setSticky:YES];
			[sensorErrorAlarm setHelpString:@"The sensor is reporting a hardware error.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
			[sensorErrorAlarm postAlarm];
		}
	}
	else {
		[sensorErrorAlarm clearAlarm];
		[sensorErrorAlarm release];
		sensorErrorAlarm = nil;
	}
	
	if(statusBits & 0x02){
		if(!countSize1Alarm){
			NSString* s = [NSString stringWithFormat:@"Bt610 (Unit %u)",[self uniqueIdNumber]];
			countSize1Alarm = [[ORAlarm alloc] initWithName:s severity:kRangeAlarm];
			[countSize1Alarm setSticky:YES];
			[countSize1Alarm setHelpString:@"The particle counter is reporting a count size 1 Alarm.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
			[countSize1Alarm postAlarm];
		}
	}
	else {
		[countSize1Alarm clearAlarm];
		[countSize1Alarm release];
		countSize1Alarm = nil;
	}
    
    if(statusBits & 0x04){
        if(!countSize2Alarm){
            NSString* s = [NSString stringWithFormat:@"Bt610 (Unit %u)",[self uniqueIdNumber]];
            countSize2Alarm = [[ORAlarm alloc] initWithName:s severity:kRangeAlarm];
            [countSize2Alarm setSticky:YES];
            [countSize2Alarm setHelpString:@"The particle counter is reporting a count size 2.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
            [countSize2Alarm postAlarm];
        }
    }
    else {
        [countSize2Alarm clearAlarm];
        [countSize2Alarm release];
        countSize2Alarm = nil;
    }
}

- (int) location
{
    return location;
}

- (void) setLocation:(int)aLocation
{
    [[[self undoManager] prepareWithInvocationTarget:self] setLocation:location];
    location = aLocation;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelLocationChanged object:self];
}

- (float) humidity
{
    return humidity;
}

- (void) setHumidity:(float)aHumidity
{
    humidity = aHumidity;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelHumidityChanged object:self];
	//plot points are added only at sample completion (see -process_response:), not here,
	//so the poll can refresh the table without adding points to the plot.
}

- (float) temperature
{
    return temperature;
}

- (void) setTemperature:(float)aTemperature
{
    temperature = aTemperature;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelTemperatureChanged object:self];
	//plot points added only at sample completion (see -process_response:), not here.
}
- (NSString*) measurementDate
{
    if(!measurementDate)return @"";
    else return measurementDate;
}

- (void) setMeasurementDate:(NSString*)aMeasurementDate
{
    [measurementDate autorelease];
    measurementDate = [aMeasurementDate copy];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelMeasurementDateChanged object:self];
}

- (NSString*) serialNumber
{
    if(!serialNumber)return @"";
    else return serialNumber;
}

- (void) setSerialNumber:(NSString*)aSerialNumber
{
    [serialNumber autorelease];
    serialNumber = [aSerialNumber copy];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelSerialNumberChanged object:self];
}

- (NSString*) softwareVersion
{
    if(!softwareVersion)return @"";
    else return softwareVersion;
}

- (void) setSoftwareVersion:(NSString*)aSoftwareVersion
{
    [softwareVersion autorelease];
    softwareVersion = [aSoftwareVersion copy];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelSoftwareVersionChanged object:self];
}

- (int) actualDuration
{
    return actualDuration;
}

- (void) setActualDuration:(int)aActualDuration
{
    actualDuration = aActualDuration;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelActualDurationChanged object:self];
}

- (float) countAlarmLimit:(int)index
{
	if(index>=0 && index<8) return countAlarmLimit[index];
	else return 0;
}

- (void) setIndex:(int)index countAlarmLimit:(float)aCountAlarmLimit
{
	if(index<0 || index>=8)return;
	[[[self undoManager] prepareWithInvocationTarget:self] setIndex:index countAlarmLimit:countAlarmLimit[index]];
    countAlarmLimit[index] = aCountAlarmLimit;
	NSMutableDictionary* userInfo = [NSMutableDictionary dictionary];
	[userInfo setObject:[NSNumber numberWithInt:index] forKey: @"Channel"];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCountAlarmLimitChanged object:self userInfo:userInfo];
}

- (float) maxCounts:(int)index
{
	if(index>=0 && index<8) return maxCounts[index];
	else return 0;
}

- (void) setIndex:(int)index maxCounts:(float)aMaxCounts
{
	if(index<0 || index>=8)return;
	[[[self undoManager] prepareWithInvocationTarget:self] setIndex:index maxCounts:maxCounts[index]];
	maxCounts[index] = aMaxCounts;
	NSMutableDictionary* userInfo = [NSMutableDictionary dictionary];
	[userInfo setObject:[NSNumber numberWithInt:index] forKey: @"Channel"];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelMaxCountsChanged object:self  userInfo:userInfo];
}

- (ORTimeRate*)timeRate:(int)index
{
	if(index>=0 && index<8) return timeRates[index];
	else return nil;
}

- (int) cycleNumber
{
    return cycleNumber;
}

- (void) setCycleNumber:(int)aCycleNumber
{
    cycleNumber = aCycleNumber;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCycleNumberChanged object:self];
}

- (NSDate*) cycleStarted
{
    return cycleStarted;
}

- (void) setCycleStarted:(NSDate*)aCycleStarted
{
    [aCycleStarted retain];
    [cycleStarted release];
    cycleStarted = aCycleStarted;
	
    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCycleStartedChanged object:self];
}

- (BOOL) running
{
    return running;
}

- (void) setRunning:(BOOL)aRunning
{
    bool changed = NO;
    if(aRunning!=running)changed=YES;
    running = aRunning;
    
    if(changed)[self setCycleStarted:[NSDate date]];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelRunningChanged object:self];
}

- (BOOL) holding
{
    return holding;
}

- (void) setHolding:(BOOL)aState
{
    holding = aState;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelRunningChanged object:self];
}

- (int) cycleDuration
{
    return cycleDuration;
}

- (void) setCycleDuration:(int)aCycleDuration
{
	if(aCycleDuration < 10) aCycleDuration = 10;
	else if(aCycleDuration > 999) aCycleDuration = 999;
    [[[self undoManager] prepareWithInvocationTarget:self] setCycleDuration:cycleDuration];
    
    cycleDuration = aCycleDuration;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCycleDurationChanged object:self];
}

- (int) numSamples
{
    return numSamples;
}

- (void) setNumSamples:(int)aNum
{
    if(aNum < 0) aNum = 0;
    else if(aNum > 1) aNum = 1;
    [[[self undoManager] prepareWithInvocationTarget:self] setNumSamples:numSamples];
    numSamples = aNum;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelNumSamplesChanged object:self];
}

- (NSString*) countingModeString
{
    if([self numSamples]>0)return [NSString stringWithFormat:@"%d Samples",numSamples];
    else                   return @"Repeating";
}

- (void) setCount:(int)index value:(int)aValue
{
	if(index>=0 && index<6){
		count[index] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelCountChanged object:self];
		//plot points added only at sample completion (see -process_response:), not here, so
		//the every-poll table refresh does not add points to the plot.
	}
}

- (int) count:(int)index
{
	if(index>=0 && index<6)return count[index];
	else return 0;
}

- (NSString*) channelSize:(int)index
{
	if(index>=0 && index<6 && channelSize[index]) return channelSize[index];
	else return @"";
}

- (void) setChannelSize:(int)index value:(NSString*)aValue
{
	if(index>=0 && index<6){
		[aValue retain];
		[channelSize[index] release];
		channelSize[index] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORBt610ModelChannelSizesChanged object:self];
	}
}

- (void) setUpPort
{
	[serialPort setSpeed:9600];
	[serialPort setParityNone];
	[serialPort setStopBits2:NO];
	[serialPort setDataBits:8];
}

- (void) firstActionAfterOpeningPort
{
	//read the channel sizes once when the port opens (the "1" report carries the parseable
	//"01, 0.3" lines) so the 610 GUI (size matrix, plot legends) and InfluxDB names are set.
	[self getUnits];
	//start the run-state heartbeat. Other settings are read only via the Sync button.
	[self pollDevice];
}

//Suppress the "Serial Port Timeout" connection alarm. The heartbeat keeps polling and
//recovers automatically when the device responds again, so command timeouts (e.g. when the
//port is closed or the device is briefly unresponsive) should not raise an alarm.
- (void) postTimeoutAlarm
{
	[self clearTimeoutAlarm];
	[self setTimeoutCount:0];
}

#pragma mark ***Archival
- (id) initWithCoder:(NSCoder*)decoder
{
	self = [super initWithCoder:decoder];
	[[self undoManager] disableUndoRegistration];
	[self setIsLog:				[decoder decodeBoolForKey:@"isLog"]];
	[self setVerbose:			[decoder decodeBoolForKey:@"verbose"]];
	[self setHoldTime:			[decoder decodeIntForKey:   @"holdTime"]];
    [self setPollTime:          [decoder decodeIntForKey:   @"pollTime"]];
	[self setTempUnits:			[decoder decodeIntForKey:   @"tempUnits"]];
	[self setCountUnits:		[decoder decodeIntForKey:   @"countUnits"]];
	[self setLocation:			[decoder decodeIntForKey:   @"location"]];
	wasRunning =				[decoder decodeBoolForKey:  @"wasRunning"];
	[self setCycleDuration:		[decoder decodeIntForKey:   @"cycleDuration"]];
	[self setNumSamples:		[decoder decodeIntForKey:   @"numSamples"]];

	int i; 
	for(i=0;i<8;i++){
		timeRates[i] = [[ORTimeRate alloc] init];
		[self setIndex:i countAlarmLimit:  	[decoder decodeFloatForKey: [NSString stringWithFormat:@"countAlarmLimit%d",i]]];
		[self setIndex:i maxCounts:			[decoder decodeFloatForKey: [NSString stringWithFormat:@"maxCounts%d",i]]];
	}
	
	[[self undoManager] enableUndoRegistration];
	
	return self;
}
- (void) encodeWithCoder:(NSCoder*)encoder
{
    [super encodeWithCoder:encoder];
    [encoder encodeBool:	isLog			forKey: @"isLog"];
    [encoder encodeBool:	verbose			forKey: @"verbose"];
    [encoder encodeInteger:	holdTime		forKey: @"holdTime"];
    [encoder encodeInteger: pollTime        forKey: @"pollTime"];
    [encoder encodeInteger:	tempUnits		forKey: @"tempUnits"];
    [encoder encodeInteger:	countUnits		forKey: @"countUnits"];
    [encoder encodeInteger:	location		forKey: @"location"];
    [encoder encodeInteger:	cycleDuration	forKey: @"cycleDuration"];
    [encoder encodeInteger:	numSamples	    forKey: @"numSamples"];
    [encoder encodeBool:	wasRunning		forKey:	@"wasRunning"];
	int i; 
	for(i=0;i<8;i++){
		[encoder encodeFloat:	countAlarmLimit[i] forKey: [NSString stringWithFormat:@"countAlarmLimit%d",i]];
		[encoder encodeFloat:	maxCounts[i]	   forKey: [NSString stringWithFormat:@"maxCounts%d",i]];

	}
}
#pragma mark *** Commands
- (void) sendNewData
{
	BTVLOG(@"Bt610(%d) action: dump new data (3)\n",[self uniqueIdNumber]);
	[self addCmdToQueue:@"3"];
}

- (void) sendAllData
{
	BTVLOG(@"Bt610(%d) action: dump all data (2)\n",[self uniqueIdNumber]);
	[self addCmdToQueue:@"2"];
}

- (void) setDate
{ 
#if defined(MAC_OS_X_VERSION_10_10) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_10 // 10.10-specific	
	unsigned unitFlags = NSCalendarUnitYear | NSCalendarUnitMonth |  NSCalendarUnitDay | NSCalendarUnitMinute | NSCalendarUnitHour;
	NSDate *today = [NSDate date];
	NSCalendar *gregorian = [[[NSCalendar alloc]  initWithCalendarIdentifier:NSCalendarIdentifierGregorian] autorelease];
#else
	unsigned unitFlags = NSYearCalendarUnit | NSMonthCalendarUnit |  NSDayCalendarUnit | NSMinuteCalendarUnit | NSHourCalendarUnit;
	NSDate *today = [NSDate date];
	NSCalendar *gregorian = [[[NSCalendar alloc]  initWithCalendarIdentifier:NSGregorianCalendar] autorelease];
#endif
	NSDateComponents *comps = [gregorian components:unitFlags fromDate:today];
	BTVLOG(@"Bt610(%d) action: set date/time (D/T)\n",[self uniqueIdNumber]);
	[self addCmdToQueue:[NSString stringWithFormat:@"D %02ld/%02ld/%02ld",[comps month],[comps day],[comps year]-2000]];
	[self addCmdToQueue:[NSString stringWithFormat:@"T %02ld:%02ld",[comps hour],[comps minute]]];
}
- (void) sendClearData				{ BTVLOG(@"Bt610(%d) action: clear data\n",[self uniqueIdNumber]); [self addCmdToQueue:@"C\rY"]; }
- (void) sendStart					{ BTVLOG(@"Bt610(%d) action: send Start (S)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"S"]; }
- (void) sendEnd					{ BTVLOG(@"Bt610(%d) action: send End (E)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"E"]; }
- (void) getSampleTime				{ BTVLOG(@"Bt610(%d) action: get sample time (ST)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"ST"]; }
- (void) getLocation				{ BTVLOG(@"Bt610(%d) action: get location (ID)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"ID"]; }
- (void) getHoldTime                { BTVLOG(@"Bt610(%d) action: get hold time (SH)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"SH"]; }
- (void) getUnits                   { BTVLOG(@"Bt610(%d) action: get units/settings report (1)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"1"]; }
- (void) getSerialNumber            { BTVLOG(@"Bt610(%d) action: get serial number (SS)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"SS"]; }
- (void) getSoftwareVersion         { BTVLOG(@"Bt610(%d) action: get software version (RV)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"RV"]; }
- (void) getLastRecord              { BTVLOG(@"Bt610(%d) action: get last record (4 1)\n",[self uniqueIdNumber]); readingLastRecord = YES; [self addCmdToQueue:@"4 1"]; }
- (void) getChannelSizes            { BTVLOG(@"Bt610(%d) action: get channel sizes (RZ)\n",[self uniqueIdNumber]); [self addCmdToQueue:@"RZ"]; }

//Set all 6 channel sizes on the device (CS command). Format not documented; sending all six
//sizes space-separated ("CS 0.3 0.5 0.7 1.0 2.5 5.0"). Verify from the log and adjust if the
//device expects a different layout.
- (void) sendChannelSizes
{
    NSMutableString* cmd = [NSMutableString stringWithString:@"CS"];
    int i;
    for(i=0;i<6;i++){
        NSString* sz = [self channelSize:i];
        NSLog(@"The channel size: %@", sz);
        [cmd appendFormat:@" %@",([sz length]>0 ? sz : @"0")];
    }
    BTVLOG(@"Bt610(%d) action: set channel sizes -> '%@'\n",[self uniqueIdNumber],cmd);
    [self addCmdToQueue:cmd];
}

- (void) sendNumSamples:(int)aValue { BTVLOG(@"Bt610(%d) action: set num samples (SN %d)\n",[self uniqueIdNumber],aValue); [self addCmdToQueue:[NSString stringWithFormat:@"SN %d",aValue]]; }
- (void) sendCountingTime:(int)aValue { BTVLOG(@"Bt610(%d) action: set sample time (ST %d)\n",[self uniqueIdNumber],aValue); [self addCmdToQueue:[NSString stringWithFormat:@"ST %d",aValue]]; }
- (void) sendID:(int)aValue			{ BTVLOG(@"Bt610(%d) action: set location (ID %d)\n",[self uniqueIdNumber],aValue); [self addCmdToQueue:[NSString stringWithFormat:@"ID %d",aValue]]; }
- (void) sendHoldTime:(int)aValue	{ BTVLOG(@"Bt610(%d) action: set hold time (SH %d)\n",[self uniqueIdNumber],aValue); [self addCmdToQueue:[NSString stringWithFormat:@"SH %d",aValue]]; }
//CU and TU must be sent as separate ESC-framed commands: the device resets its input
//buffer on every ESC, so combining them in one frame discards all but the last command.
- (void) sendCountUnits:(int)aCountUnit	{ BTVLOG(@"Bt610(%d) action: set count units (CU %d)\n",[self uniqueIdNumber],aCountUnit); [self addCmdToQueue:[NSString stringWithFormat:@"CU %d",aCountUnit]]; }
- (void) sendTempUnits:(int)aTempUnit	{ BTVLOG(@"Bt610(%d) action: set temp units (TU %d)\n",[self uniqueIdNumber],aTempUnit); [self addCmdToQueue:[NSString stringWithFormat:@"TU %d",aTempUnit]]; }
- (void) probe						{ probing = YES; [self getOpStatus]; }
- (void) getOpStatus                { [self addCmdToQueue:@"OP"]; }

//push all ORCA-configured settings to the device (mirrors PMS31 -writeSettingsToDevice)
- (void) writeSettingsToDevice
{
	if([serialPort isOpen]){
		BTVLOG(@"Bt610(%d) action: load all ORCA settings to device\n",[self uniqueIdNumber]);
		[self setDate];
		[self sendID:location];
		[self sendHoldTime:holdTime];
		[self sendNumSamples:numSamples];
		[self sendTempUnits:tempUnits];
        [self sendCountUnits:countUnits];
		[self sendCountingTime:cycleDuration];
	}
}

//query the device for identity + all settings, then print a consolidated summary
- (void) probeModel
{
	if([serialPort isOpen]){
		NSLog(@"Bt610(%d): Probing model (serial #, software version, settings)...\n",[self uniqueIdNumber]);
		[self getSerialNumber];    //SS
		[self getSoftwareVersion]; //RV
		[self getUnits];           //CU, TU
		[self getSampleTime];      //ST
		[self getHoldTime];        //SH
		[self getLocation];        //ID
		//give the replies time to arrive, then print everything the model now holds
		[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(printModelSummary) object:nil];
		[self performSelector:@selector(printModelSummary) withObject:nil afterDelay:3];
	}
	else NSLog(@"Bt610(%d): Serial Port not open. Cannot probe model.\n",[self uniqueIdNumber]);
}

- (void) printModelSummary
{
	NSString* cu = @"?";
	if(countUnits==0)      cu = @"Counts/Ft^3";
	else if(countUnits==1) cu = @"Counts/L";
	else if(countUnits==2) cu = @"Total Counts";
	else if(countUnits==3) cu = @"Counts/M^3";

	NSLog(@"========== Bt610(%d) Model Probe ==========\n",[self uniqueIdNumber]);
	NSLog(@"Serial Number   : %@\n",[self serialNumber]);
	NSLog(@"Software Version: %@\n",[self softwareVersion]);
	NSLog(@"Count Units     : %@ (%d)\n",cu,countUnits);
	NSLog(@"Temp Units      : %@ (%d)\n",tempUnits==0?@"C":@"F",tempUnits);
	NSLog(@"Start Time (ST) : %d s\n",cycleDuration);
	NSLog(@"Hold Time (SH)  : %d s\n",holdTime);
	NSLog(@"Num Samples (SN): %d%@\n",numSamples,numSamples==0?@" (repeat)":@"");
	NSLog(@"Location ID     : %d\n",location);
	NSLog(@"===========================================\n");
}

#pragma mark ***Polling and Cycles
- (void) startCycle
{
    [self startCycle:NO];
}
- (void) startCycle:(BOOL)force
{
	if((![self running] || force) && [serialPort isOpen]){
		[self sendEnd];
        [self enqueueCmd:@"++Delay"];
		[self setCycleNumber:0];   //first counting cycle will bump this to 1 (see OP handler)
		wasCounting = NO;

		//On Start, push ALL ORCA settings to the machine (overwriting whatever is there),
		//then begin the run so the counter always runs with ORCA's configuration.
		[self writeSettingsToDevice];   //push settings only (channel sizes are read on port open)
        [self enqueueCmd:@"++Delay"];

		[self sendStart];
        [self enqueueCmd:@"++Delay"];
        [self startDataArrivalTimeout];
		NSLog(@"Bt610(%d) Detection started: %@ \n",[self uniqueIdNumber], [self countingModeString]); //always logged (not gated by verbose)
        [self checkCycle];
	}
}



- (void) stopCycle
{
	if([self running] && [serialPort isOpen]){
		//log the completed cycle count BEFORE resetting it to 0
		NSLog(@"Bt610(%d) Detection ended. Number of Cycles %d\n",[self uniqueIdNumber], [self cycleNumber]);
		[self setCycleNumber:0];
		[self sendEnd];
        [self cancelDataArrivalTimeout];
	}
}


#pragma mark •••Bit Processing Protocol
- (void) processIsStarting
{
	if(!running){
		if(!sentStartOnce){
		   sentStartOnce = YES;
		   sentStopOnce = NO;
            wasRunning = NO;

			[self startCycle:YES];
		}
	}
    else wasRunning = YES;
}

- (void) processIsStopping
{
	if(!wasRunning){
		if(!sentStopOnce){
			sentStopOnce = YES;
			sentStartOnce = NO;
			[self stopCycle];
		}
	}
}

//note that everything called by these routines MUST be threadsafe
- (void) startProcessCycle
{    
	@try { 
	}
	@catch(NSException* localException) { 
		//catch this here to prevent it from falling thru, but nothing to do.
	}
}

- (void) endProcessCycle
{
}

- (NSString*) identifier
{
	NSString* s;
 	@synchronized(self){
		s= [NSString stringWithFormat:@"Bt610,%u",[self uniqueIdNumber]];
	}
	return s;
}

- (NSString*) processingTitle
{
	NSString* s;
 	@synchronized(self){
		s= [self identifier];
	}
	return s;
}

- (double) convertedValue:(int)aChan
{
	double theValue = 0;
	@synchronized(self){
		if(aChan<6)			theValue = [self count:aChan];
		else if(aChan==6)	theValue = [self temperature];
		else if(aChan==7)	theValue = [self humidity];
	}
	return theValue;
}

- (double) maxValueForChan:(int)aChan
{
	double theValue;
	@synchronized(self){
		theValue = (double)[self maxCounts:aChan]; 
	}
	return theValue;
}

- (double) minValueForChan:(int)aChan
{
	return 0;
}

- (void) getAlarmRangeLow:(double*)theLowLimit high:(double*)theHighLimit channel:(int)channel
{
	@synchronized(self){
		*theLowLimit = -.001;
		*theHighLimit =  [self countAlarmLimit:channel]; 
	}		
}

- (BOOL) processValue:(int)channel
{
	BOOL r;
	@synchronized(self){
		r = YES;    //temp -- figure out what the process bool for this object should be.
	}
	return r;
}

- (void) setProcessOutput:(int)channel value:(int)value
{
    //nothing to do. not used in adcs. really shouldn't be in the protocol
}

- (BOOL) dataForChannelValid:(int)aChannel
{
    return [self isValid] && [serialPort isOpen];
}

@end

@implementation ORBt610Model (private)

- (void) postCouchDBRecord
{    
    NSDictionary* values = [NSDictionary dictionaryWithObjectsAndKeys:
                            [NSArray arrayWithObjects:
                                [NSNumber numberWithInt:count[0]],
                                [NSNumber numberWithInt:count[1]],
                                [NSNumber numberWithInt:count[2]],
                                [NSNumber numberWithInt:count[3]],
                                [NSNumber numberWithInt:count[4]],
                                [NSNumber numberWithInt:count[5]],
                                nil], @"counts",
                            [NSArray arrayWithObjects:
                                 [NSNumber numberWithInt:countAlarmLimit[0]],
                                 [NSNumber numberWithInt:countAlarmLimit[1]],
                                 [NSNumber numberWithInt:countAlarmLimit[2]],
                                 [NSNumber numberWithInt:countAlarmLimit[3]],
                                 [NSNumber numberWithInt:countAlarmLimit[4]],
                                 [NSNumber numberWithInt:countAlarmLimit[5]],
                                 nil], @"countLimits",
                            [NSNumber numberWithFloat:  temperature],       @"temperature",
                            [NSNumber numberWithFloat:  humidity],         @"humidity",
                            [NSNumber numberWithInt:    actualDuration],   @"actualDuration",
                            [NSNumber numberWithInt:    statusBits],       @"statusBits",
                            [NSNumber numberWithInt:    cycleDuration],    @"pollTime",
                            nil];
    [[NSNotificationCenter defaultCenter] postNotificationName:@"ORCouchDBAddObjectRecord" object:self userInfo:values];
}

//Send the completed measurement to InfluxDB (mirrors PMS31 -sendPMS31ToInfluxDBnPlot).
//Called ONLY at sample completion, so one record is sent per finished measurement.
- (void) sendToInfluxDB
{
    @autoreleasepool {
        @try {
            InFluxDB = [[[(ORAppDelegate*)[NSApp delegate] document] findObjectWithFullID:@"ORInFluxDBModel,1"] retain];
            if(InFluxDB == nil) return; //InfluxDB object not in config — nothing to send

            double currentTimeStamp = [[NSDate date] timeIntervalSince1970];
            ORInFluxDBMeasurement* measurement = [ORInFluxDBMeasurement measurementForBucket:@"ENAP_SC_UNC" org:[InFluxDB org]];

            [measurement start:@"BT610_ParticleCounts"];
            [measurement addTag:@"unit" withString:[NSString stringWithFormat:@"%u",[self uniqueIdNumber]]];
            [measurement addTag:@"mode" withString:[self countingModeString]];

            //channel field names come from the device (RZ) rather than being hardcoded
            NSArray* fallbackNames = @[@"0.3um",@"0.5um",@"0.7um",@"1.0um",@"2.5um",@"5.0um"];
            int i;
            for(i=0;i<6;i++){
                NSString* sz = [self channelSize:i];
                NSString* fieldName = ([sz length]>0) ? [NSString stringWithFormat:@"%@um",sz]
                                                       : [fallbackNames objectAtIndex:i];
                [measurement addField:fieldName withLong:(long)[self count:i]];
            }
            [measurement addField:@"temperature" withDouble:temperature];
            [measurement addField:@"humidity"    withDouble:humidity];

            [measurement setTimeStamp:currentTimeStamp];
            [InFluxDB executeDBCmd:measurement];
            [InFluxDB release];
            InFluxDB = nil;
        }
        @catch (NSException* exception) {
            NSLog(@"Bt610(%d): InfluxDB error: %@\n",[self uniqueIdNumber],[exception reason]);
            [InFluxDB release];
            InFluxDB = nil;
        }
    }
}

//Continuous heartbeat: runs the whole time the port is open (independent of whether
//ORCA started the run) so that starting/stopping or changing settings directly on the
//machine is always reflected back into ORCA.
- (void) pollDevice
{
    if([serialPort isOpen]){
        //only poll run-state (start/stop from the machine + live counts). Settings are
        //NEVER auto-synced — that happens only via the Sync Settings button.
        if(!dumpInProgress){
            [self probe];              //OP -> running/holding/stopped
        }
        //Floor the interval: a 0/unset pollTime would reschedule with afterDelay:0, creating a
        //runaway loop that floods the command queue with OP probes and starves Start.
        int delay = (pollTime > 0) ? pollTime : 5;
        [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollDevice) object:nil];
        [self performSelector:@selector(pollDevice) withObject:nil afterDelay:delay];
    }
}

//read the machine's current settings back into ORCA (CU/TU -> units, ST -> start time,
//SH -> hold time). Responses are parsed in -process_response:.
- (void) readSettingsFromDevice
{
    if([serialPort isOpen]){
        //Individual setting queries (device replies "<CMD> <value>", e.g. "SH 20", "CU 1-/L").
        [self addCmdToQueue:@"CU"];   //count units
        [self addCmdToQueue:@"TU"];   //temp units
        [self getSampleTime];         //ST -> start/sample time
        [self getHoldTime];           //SH -> hold time
        [self addCmdToQueue:@"SN"];   //number of samples / mode
        //Command "1" returns the identity report (serial #, firmware version).
        [self getUnits];
    }
}

- (void) checkCycle
{
	if([serialPort isOpen]){
        if(!dumpInProgress)[self probe];
        [self cancelCycleCheck];
        [self performSelector:@selector(checkCycle) withObject:nil afterDelay:1];
    }
}
- (void) cancelCycleCheck
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(checkCycle) object:nil];
}

- (void) startDataArrivalTimeout
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(doCycleKick) object:nil];
    [self performSelector:@selector(doCycleKick)  withObject:nil afterDelay:(cycleDuration+20)];
}

- (void) cancelDataArrivalTimeout
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(doCycleKick) object:nil];
}

- (void) doCycleKick
{
    [self setMissedCycleCount:missedCycleCount+1];
    NSLogColor([NSColor redColor],@"%@ data did not arrive at end of cycle (missed %d)\n",[self fullID],missedCycleCount);
    if(numSamples==0){ //repeating mode
        NSLogColor([NSColor redColor],@"Kickstarting %@\n",[self fullID]);
        [self setCount:0 value:0];
        [self setCount:1 value:0];
        [self setCount:2 value:0];
        [self setCount:3 value:0];
        [self setCount:4 value:0];
        [self setCount:5 value:0];       
        [self setTemperature:0];
        [self setHumidity:0];
        [self setIsValid:NO];

        [self stopCycle];
        [self startCycle:YES];
    }
}


- (void) addCmdToQueue:(NSString*)aCmd
{
	if([serialPort isOpen]){ 
        aCmd = [aCmd stringByReplacingOccurrencesOfString:@"\n" withString:@""];
        aCmd = [aCmd stringByReplacingOccurrencesOfString:@"\r" withString:@""];
        int esc = 27;

        aCmd = [NSString stringWithFormat:@"%c%@\r",esc,aCmd];
		
		[self enqueueCmd:aCmd];
		[self enqueueCmd:@"++Delay"];
		
		if(!lastRequest){
			[self processOneCommandFromQueue];
		}
	}
	else NSLog(@"Bt610 (%d): Serial Port not open. Cmd Ignored.\n",[self uniqueIdNumber]);
}

- (void) process_response:(NSString*)theResponse
{
	[self setIsValid:YES];
    theResponse = [theResponse stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
    theResponse = [theResponse stringByTrimmingCharactersInSet:[NSCharacterSet controlCharacterSet]];
	NSArray* partsByComma = [theResponse componentsSeparatedByString:@","];
	if([partsByComma count] >= 14 && (![lastRequest hasPrefix:@"2"] && ![lastRequest hasPrefix:@"3"])){
		if(!dumpInProgress){
            [self setMeasurementDate:[partsByComma objectAtIndex:0]];
			[self setCount:0 value:[[partsByComma objectAtIndex:2] intValue]];
			[self setCount:1 value:[[partsByComma objectAtIndex:4] intValue]];
			[self setCount:2 value:[[partsByComma objectAtIndex:6] intValue]];
			[self setCount:3 value:[[partsByComma objectAtIndex:8] intValue]];
			[self setCount:4 value:[[partsByComma objectAtIndex:10] intValue]];
			[self setCount:5 value:[[partsByComma objectAtIndex:12] intValue]];
			
			[self setTemperature:[[partsByComma objectAtIndex:13] floatValue]];
			[self setHumidity:[[partsByComma objectAtIndex:14] floatValue]];
			[self setLocation:[[partsByComma objectAtIndex:15] floatValue]];

			[self setActualDuration:[[partsByComma objectAtIndex:16] intValue]];
            
            NSString* statusString = [[partsByComma objectAtIndex:19] stringByReplacingOccurrencesOfString:@"*" withString:@""]; //remove the leading '*'
			[self setStatusBits:[statusString intValue]];
            
            [self setMissedCycleCount:0];
            [self cancelDataArrivalTimeout];

            //add plot points ONLY here (at sample completion / Hold), not on every poll
            {
                int ch;
                for(ch=0;ch<6;ch++){
                    if(timeRates[ch] == nil) timeRates[ch] = [[ORTimeRate alloc] init];
                    [timeRates[ch] addDataToTimeAverage:count[ch]];
                }
                if(timeRates[6] == nil) timeRates[6] = [[ORTimeRate alloc] init];
                [timeRates[6] addDataToTimeAverage:temperature];
                if(timeRates[7] == nil) timeRates[7] = [[ORTimeRate alloc] init];
                [timeRates[7] addDataToTimeAverage:humidity];
            }

            [self postCouchDBRecord];
            [self sendToInfluxDB]; //send one InfluxDB record per finished measurement

            //Only re-arm the data-arrival watchdog in Repeat mode (numSamples==0), where more
            //records are expected. In Single/N-sample mode the device stops after the last
            //sample, so re-arming would fire doCycleKick and raise a false "missing cycles" alarm.
            if(numSamples==0) [self startDataArrivalTimeout];
            //NOTE: cycle number is incremented when the NEXT counting begins (Hold->Running
            //transition in the OP handler below), not here at sample completion.

            [self probe];
		}
		else {
			theResponse = [theResponse stringByReplacingOccurrencesOfString:@"\n" withString:@""];
			theResponse = [theResponse stringByReplacingOccurrencesOfString:@"\r" withString:@""];
			//put in a unix time stamp for convenience
			NSString* aDate = [partsByComma objectAtIndex:0];
			
			NSDateFormatter* dateFormatter = [[[NSDateFormatter alloc] init] autorelease];
			[dateFormatter setDateFormat:@"dd-MMM-yyyy HH:mm:ss"];
			NSDate* gmtTime = [dateFormatter dateFromString:aDate];
			NSNumber *timestamp=[[[NSNumber alloc] initWithDouble:[gmtTime timeIntervalSince1970]] autorelease];
			
			NSLog(@"%d, %@, %@\n",dumpCount,timestamp,theResponse);
			[self setDumpCount:dumpCount+1];
			[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(dumpTimeout) object:nil];
			[self performSelector:@selector(dumpTimeout) withObject:nil afterDelay:.5];
		}
	}
	else {
		if([lastRequest hasPrefix:@"2"] || [lastRequest hasPrefix:@"3"]){
			[self setDumpInProgress:YES];
			[self setDumpCount:0];
			[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(dumpTimeout) object:nil];
			[self performSelector:@selector(dumpTimeout) withObject:nil afterDelay:.5];
		}
		else if([theResponse hasPrefix:@"SERIAL NUMBER"]){
			//"1" report line: "SERIAL NUMBER, A15436"
			NSRange r = [theResponse rangeOfString:@","];
			if(r.location != NSNotFound){
				[self setSerialNumber:[[theResponse substringFromIndex:r.location+1]
									   stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]]];
			}
		}
		else if([theResponse hasPrefix:@"BT-610,"]){
			//"1" report line: "BT-610, 81666-1, R1.1.2" -> software/firmware version = last field
			NSArray* p = [theResponse componentsSeparatedByString:@","];
			if([p count]>=3){
				[self setSoftwareVersion:[[p lastObject]
										 stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]]];
			}
		}
		else if([theResponse hasPrefix:@"CU"]){
			//count units reply "CU 1-/L" (index-token). The leading number is the unit index.
			NSString* u = [[theResponse substringFromIndex:2]
						   stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" ,\t"]];
			if([u length]>0 && [[NSCharacterSet decimalDigitCharacterSet] characterIsMember:[u characterAtIndex:0]]){
				[self setCountUnits:[u intValue]];
			}
			else if([u hasPrefix:@"CF"]) [self setCountUnits:0];
			else if([u hasPrefix:@"/L"]) [self setCountUnits:1];
			else if([u hasPrefix:@"TC"]) [self setCountUnits:2];
			else if([u hasPrefix:@"M3"]) [self setCountUnits:3];
		}
		else if([theResponse hasPrefix:@"ST"]){
			NSArray* partsBySpaces = [theResponse componentsSeparatedByString:@" "];
			if([partsBySpaces count]==2){
				NSString* st = [partsBySpaces objectAtIndex:1];
				[self setCycleDuration:[st intValue]];
			}
		}
		else if([theResponse hasPrefix:@"TU"]){
			//temp units reply "TU 1-F" (index-token). The leading number is the unit index.
			NSString* u = [[theResponse substringFromIndex:2]
						   stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" ,\t"]];
			if([u length]>0 && [[NSCharacterSet decimalDigitCharacterSet] characterIsMember:[u characterAtIndex:0]]){
				[self setTempUnits:[u intValue]];
			}
			else if([u hasPrefix:@"F"]) [self setTempUnits:1];
			else                        [self setTempUnits:0];
		}
		else if([theResponse hasPrefix:@"SH"]){
			NSArray* partsBySpaces = [theResponse componentsSeparatedByString:@" "];
			if([partsBySpaces count]==2){
				NSString* st = [partsBySpaces objectAtIndex:1];
				[self setHoldTime:[st intValue]];
			}
		}
		else if([theResponse hasPrefix:@"SN"]){
			//number of samples / mode reply: "SN <n>" (0=Repeat). Read only on Sync.
			NSArray* partsBySpaces = [theResponse componentsSeparatedByString:@" "];
			if([partsBySpaces count]==2){
				[self setNumSamples:[[partsBySpaces objectAtIndex:1] intValue]];
			}
		}
		else if([theResponse hasPrefix:@"SS"] || [lastRequest isEqualToString:@"SS"]){
			//serial number reply. In Computer Mode the device may omit the "SS" echo,
			//so also match on lastRequest. Strip any "SS" prefix + comma/space separator.
			NSString* sn = theResponse;
			if([sn hasPrefix:@"SS"]) sn = [sn substringFromIndex:2];
			sn = [sn stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" ,\t"]];
			[self setSerialNumber:sn];
		}
		else if([theResponse hasPrefix:@"RV"] || [lastRequest isEqualToString:@"RV"]){
			//software revision reply. In Computer Mode the device may omit the "RV" echo,
			//so also match on lastRequest. Strip any "RV" prefix + comma/space separator.
			NSString* rv = theResponse;
			if([rv hasPrefix:@"RV"]) rv = [rv substringFromIndex:2];
			rv = [rv stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@" ,\t"]];
			[self setSoftwareVersion:rv];
		}
		else if([partsByComma count]==2){
			//channel size line "01, 0.3" (from RZ, and from the "1" report): "<chNum 1-6>, <size>".
			//Guard tightly: first field must be a 1-2 digit integer 1..6 with no decimal point.
			NSString* f0 = [[partsByComma objectAtIndex:0] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
			int chNum = [f0 intValue];
			if(chNum>=1 && chNum<=6 && [f0 length]<=2 && [f0 rangeOfString:@"."].location==NSNotFound){
				NSString* size = [[partsByComma objectAtIndex:1] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
				[self setChannelSize:chNum-1 value:size];
			}
		}
        else if([theResponse  isEqualToString:@"S"]){
            [self setRunning:YES];
        }
        else if([theResponse isEqualToString:@"E"]){
            [self setRunning:NO];
        }
        else if([theResponse hasPrefix:@"OP"]){
            NSArray* partsBySpaces = [theResponse componentsSeparatedByString:@" "];
            if([partsBySpaces count]>1){
                NSString* state = [partsBySpaces objectAtIndex:1];
                if([state hasPrefix:@"R"]){ //counting
                    if(!wasCounting){
                        //transition INTO counting -> a new counting cycle is starting.
                        //(In Repeat mode the idle between counts reports S/H, so this fires
                        //once per counting cycle and is never reset to 1 mid-run.)
                        [self setCycleNumber:[self cycleNumber]+1];
                        [self startDataArrivalTimeout];
                        [self checkCycle];
                    }
                    wasCounting = YES;
                    [self setHolding:NO];
                    [self setRunning:YES];
                    if([partsBySpaces count]>2){
                        [self setOpTimer:[partsBySpaces objectAtIndex:2]];
                    }
                }
                else if([state hasPrefix:@"H"]){ //holding (idle between counts)
                    wasCounting = NO;
                    [self setHolding:YES];
                    if([partsBySpaces count]>2){
                        [self setOpTimer:[partsBySpaces objectAtIndex:2]];
                    }
                }
                else if([state hasPrefix:@"S"]){ //stopped / idle between counts
                    wasCounting = NO;
                    [self setRunning:NO];
                    [self setHolding:NO];
                    [self setOpTimer:@""];
                    [self cancelCycleCheck];
                }
            }
        }
	}
	[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(timeout) object:nil];
}



- (void) clearDelay
{
	delay = NO;
	[self processOneCommandFromQueue];
}

- (void) dumpTimeout
{
	[self setDumpInProgress:NO];
	[self setDumpCount:0];
	[self setLastRequest:nil];			 //clear the last request
	[self processOneCommandFromQueue];	 //do the next command in the queue

	NSLog(@"Bt610 (%d): Data printout finished\n",[self uniqueIdNumber]);
}

- (void) processOneCommandFromQueue
{
    if(delay)return;
	
	NSString* aCmd = [self nextCmd];
	if(aCmd){
		if([aCmd isEqualToString:@"++Delay"]){
			delay = YES;
			[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(clearDelay) object:nil];
			[self performSelector:@selector(clearDelay) withObject:nil afterDelay:kBt610DelayTime];
		}
		else {
			[self startTimeout:3];
            NSString* s = [aCmd stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
            s = [aCmd stringByTrimmingCharactersInSet:[NSCharacterSet controlCharacterSet]];

			[self setLastRequest:s];
			[serialPort writeString:aCmd];
		}
	}
}

@end
