//--------------------------------------------------------
// ORBt610Controller
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

#import "ORBt610Controller.h"
#import "ORBt610Model.h"
#import "ORTimeLinePlot.h"
#import "ORCompositePlotView.h"
#import "ORTimeAxis.h"
#import "ORTimeRate.h"
#import "ORSerialPortController.h"

@implementation ORBt610Controller

#pragma mark ***Initialization

- (id) init
{
	self = [super initWithWindowNibName:@"Bt610"];
	return self;
}

- (void) dealloc
{
	[[NSNotificationCenter defaultCenter] removeObserver:self];
    [blankView release];
	[super dealloc];
}

//recursively find a standalone (non-popup) NSTextField whose stringValue matches aString
- (NSTextField*) findTextFieldWithString:(NSString*)aString inView:(NSView*)aView
{
	if(aView == nil) return nil;
	for(NSView* sub in [aView subviews]){
		if([sub isKindOfClass:[NSTextField class]] &&
		   ![sub isKindOfClass:[NSPopUpButton class]] &&
		   [[(NSTextField*)sub stringValue] isEqualToString:aString]){
			return (NSTextField*)sub;
		}
		NSTextField* found = [self findTextFieldWithString:aString inView:sub];
		if(found) return found;
	}
	return nil;
}

- (void) awakeFromNib
{

    [[plotter0 yAxis] setRngLow:0.0 withHigh:100.];
	[[plotter0 yAxis] setRngLimitsLow:0 withHigh:10000000. withMinRng:5];
	
    [[plotter0 xAxis] setRngLow:0.0 withHigh:10000];
	[[plotter0 xAxis] setRngLimitsLow:0.0 withHigh:200000. withMinRng:200];
	
	ORTimeLinePlot* aPlot = [[ORTimeLinePlot alloc] initWithTag:0 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor redColor]];
	[aPlot setName:@"0.3 µm"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:1 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor greenColor]];
	[aPlot setName:@"0.5 µm"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:2 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor blueColor]];
	[aPlot setName:@"0.7 µm"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:3 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor blackColor]];
	[aPlot setName:@"1.0 µm"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:4 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor cyanColor]];
	[aPlot setName:@"2.0 µm"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:5 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor orangeColor]];
	[aPlot setName:@"3.0 µm"];
	[aPlot release];

	aPlot = [[ORTimeLinePlot alloc] initWithTag:6 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor brownColor]];
	[aPlot setName:@"Temp"];
	[aPlot release];
	
	aPlot = [[ORTimeLinePlot alloc] initWithTag:7 andDataSource:self];
	[plotter0 addPlot: aPlot];
	[aPlot setLineColor:[NSColor purpleColor]];
	[aPlot setName:@"Humidity"];
	[aPlot release];
	
	
	[plotter0 setShowLegend:YES];

	[(ORTimeAxis*)[plotter0 xAxis] setStartTime: [[NSDate date] timeIntervalSince1970]];

	int i;
	for(i=0;i<8;i++){
		[[countAlarmLimitMatrix cellAtRow:i column:0] setTag:i];
		[[maxCountsMatrix cellAtRow:i column:0] setTag:i];
	}

	//relabel the "Duration:" field to "Start Time:" (the ST sample-time setting).
	//Done in code because the runtime nib is a compiled NIBArchive that can't be
	//safely byte-edited; the cycleDurationField's sibling label is the target.
	for(NSView* aView in [[cycleDurationField superview] subviews]){
		if([aView isKindOfClass:[NSTextField class]] &&
		   [[(NSTextField*)aView stringValue] isEqualToString:@"Duration:"]){
			[(NSTextField*)aView setStringValue:@"Start Time:"];
			break;
		}
	}

	//if the units display field wasn't connected in the nib, locate it at runtime by its
	//default title so -countUnitsChanged: can still update it (no IB outlet required).
	if(unitsField == nil){
		unitsField = [self findTextFieldWithString:@"Counts/Ft^3" inView:totalView];
		if(unitsField == nil) unitsField = [self findTextFieldWithString:@"Counts/Ft^3" inView:tabView];
		if(unitsField == nil) unitsField = [self findTextFieldWithString:@"Counts/Ft^3" inView:[[self window] contentView]];
	}

	blankView = [[NSView alloc] init];
    basicOpsSize	= NSMakeSize(422,528);
    processOpsSize	= NSMakeSize(422,370);
    historyOpsSize	= NSMakeSize(422,480);
	
	NSString* key = [NSString stringWithFormat: @"orca.ORRad7%u.selectedtab",[model uniqueIdNumber]];
    NSInteger index = [[NSUserDefaults standardUserDefaults] integerForKey: key];
	if((index<0) || (index>[tabView numberOfTabViewItems]))index = 0;
	[tabView selectTabViewItemAtIndex: index];
	
	NSUInteger style = [[self window] styleMask];
	if(index == 2){
		[[self window] setStyleMask: style | NSWindowStyleMaskResizable];
	}
	else {
		[[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
	}
	
	
	[super awakeFromNib];
}

- (void) setModel:(id)aModel
{
	[super setModel:aModel];
	[[self window] setTitle:[NSString stringWithFormat:@"Bt610 (Unit %u)",[model uniqueIdNumber]]];
}
- (BOOL) portLocked
{
	return [gSecurity isLocked:ORBt610Lock];;
}

#pragma mark ***Notifications

- (void) registerNotificationObservers
{
	NSNotificationCenter* notifyCenter = [NSNotificationCenter defaultCenter];
    [super registerNotificationObservers];
    [notifyCenter addObserver : self
                     selector : @selector(lockChanged:)
                         name : ORRunStatusChangedNotification
                       object : nil];
    
    [notifyCenter addObserver : self
                     selector : @selector(lockChanged:)
                         name : ORBt610Lock
                        object: nil];

    [notifyCenter addObserver : self
                     selector : @selector(countChanged:)
                         name : ORBt610ModelCountChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(numSamplesChanged:)
                         name : ORBt610ModelNumSamplesChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleDurationChanged:)
                         name : ORBt610ModelCycleDurationChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(runningChanged:)
                         name : ORBt610ModelRunningChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleStartedChanged:)
                         name : ORBt610ModelCycleStartedChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleNumberChanged:)
                         name : ORBt610ModelCycleNumberChanged
						object: model];

    [notifyCenter addObserver : self
					 selector : @selector(scaleAction:)
						 name : ORAxisRangeChangedNotification
					   object : nil];
	
    [notifyCenter addObserver : self
					 selector : @selector(miscAttributesChanged:)
						 name : ORMiscAttributesChanged
					   object : model];
	
    [notifyCenter addObserver : self
					 selector : @selector(updateTimePlot:)
						 name : ORRateAverageChangedNotification
					   object : nil];
	
    [notifyCenter addObserver : self
                     selector : @selector(maxCountsChanged:)
                         name : ORBt610ModelMaxCountsChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(countAlarmLimitChanged:)
                         name : ORBt610ModelCountAlarmLimitChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(temperatureChanged:)
                         name : ORBt610ModelTemperatureChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(humidityChanged:)
                         name : ORBt610ModelHumidityChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(statusBitsChanged:)
                         name : ORBt610ModelStatusBitsChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(countUnitsChanged:)
                         name : ORBt610ModelCountUnitsChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(tempUnitsChanged:)
                         name : ORBt610ModelTempUnitsChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(holdTimeChanged:)
                         name : ORBt610ModelHoldTimeChanged
						object: model];
    [notifyCenter addObserver : self
                     selector : @selector(pollTimeChanged:)
                         name : ORBt610ModelPollTimeChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(isLogChanged:)
                         name : ORBt610ModelIsLogChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(verboseChanged:)
                         name : ORBt610ModelVerboseChanged
						object: model];
	
    [notifyCenter addObserver : self
                     selector : @selector(actualDurationChanged:)
                         name : ORBt610ModelActualDurationChanged
						object: model];	

    [notifyCenter addObserver : self
                     selector : @selector(timedOutChanged:)
                         name : ORSerialPortWithQueueModelTimeoutCountChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(dumpInProgressChanged:)
                         name : ORBt610ModelDumpInProgressChanged
						object: model];

    [notifyCenter addObserver : self
                     selector : @selector(dumpCountChanged:)
                         name : ORBt610ModelDumpCountChanged
						object: model];
    
    [notifyCenter addObserver : self
                     selector : @selector(opTimerChanged:)
                         name : ORBt610ModelOpTimerChanged
                        object: model];
    
    [notifyCenter addObserver : self
                     selector : @selector(measurementDateChanged:)
                         name : ORBt610ModelMeasurementDateChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(serialNumberChanged:)
                         name : ORBt610ModelSerialNumberChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(softwareVersionChanged:)
                         name : ORBt610ModelSoftwareVersionChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(channelSizesChanged:)
                         name : ORBt610ModelChannelSizesChanged
                        object: model];

	[serialPortController registerNotificationObservers];
	
}

- (void) updateWindow
{
    [super updateWindow];
    [self lockChanged:nil];
	[self countChanged:nil];
    [self opTimerChanged:nil];
	[self numSamplesChanged:nil];
	[self cycleDurationChanged:nil];
    [self measurementDateChanged:nil];
    [self serialNumberChanged:nil];
    [self softwareVersionChanged:nil];
    [self channelSizesChanged:nil];
	[self runningChanged:nil];
	[self cycleStartedChanged:nil];
	[self cycleNumberChanged:nil];
	[self updateTimePlot:nil];
    [self miscAttributesChanged:nil];
	[self maxCountsChanged:nil];
	[self countAlarmLimitChanged:nil];
	[self temperatureChanged:nil];
	[self humidityChanged:nil];
	[self statusBitsChanged:nil];
	[self countUnitsChanged:nil];
	[self tempUnitsChanged:nil];
	[self holdTimeChanged:nil];
	[self isLogChanged:nil];
	[self verboseChanged:nil];
	[self actualDurationChanged:nil];
	[self timedOutChanged:nil];
	[self dumpInProgressChanged:nil];
	[self dumpCountChanged:nil];
	[serialPortController updateWindow];
}
- (void) opTimerChanged:(NSNotification*)aNote
{
    [opTimerField setStringValue:[model opTimer]];
}

- (void) serialNumberChanged:(NSNotification*)aNote
{
    [serialNumberField setStringValue: [model serialNumber]];
}

- (void) softwareVersionChanged:(NSNotification*)aNote
{
    [softwareVersionField setStringValue: [model softwareVersion]];
}

- (void) channelSizesChanged:(NSNotification*)aNote
{
    //Populate the channel-size matrix and the plot legends from the device (RZ) instead of
    //hardcoded sizes. Use [matrix cells] (row-major) so it works regardless of whether the
    //matrix is laid out as rows or columns.
    NSArray* cells = [channelSizeMatrix cells];
    NSArray* editCells = [channelSizeEditMatrix cells];  //editable copy in Advanced Setting
    int i;
    for(i=0;i<6;i++){
        NSString* sz = [model channelSize:i];
        if(i < (int)[cells count]) [[cells objectAtIndex:i] setStringValue:sz];
        if(i < (int)[editCells count]) [[editCells objectAtIndex:i] setStringValue:sz];
        if([sz length]>0){
            [(ORTimeLinePlot*)[plotter0 plotWithTag:i] setName:[NSString stringWithFormat:@"%@ µm",sz]];
        }
    }
    [channelSizeMatrix setNeedsDisplay:YES];
    [channelSizeEditMatrix setNeedsDisplay:YES];
    //setName: only stores the name; force the legend to re-lay-out with the new names
    [plotter0 setShowLegend:YES];
    [plotter0 setNeedsDisplay:YES];
}

- (void) measurementDateChanged:(NSNotification*)aNote
{
    [measurementDateField setStringValue: [model measurementDate]];
}

- (void) dumpCountChanged:(NSNotification*)aNote
{
	[dumpCountField setIntValue: [model dumpCount]];
}

- (void) dumpInProgressChanged:(NSNotification*)aNote
{
	[dumpInProgressField setStringValue: [model dumpInProgress]?@"Printing":@"--"];
}

- (void) timedOutChanged:(NSNotification*)aNote
{
	[timedOutField setStringValue: [model timeoutCount]!=0 ? @"Last Command Timed Out":@""];
}

- (void) isLogChanged:(NSNotification*)aNote
{
	[isLogCB setIntValue: [model isLog]];
	[[plotter0 yAxis] setLog:[model isLog]];
	[plotter0 setNeedsDisplay:YES];
}

- (void) verboseChanged:(NSNotification*)aNote
{
	[verboseCB setIntValue: [model verbose]];
}

- (void) holdTimeChanged:(NSNotification*)aNote
{
	[holdTimeField setIntValue: [model holdTime]];
}

- (void) pollTimeChanged:(NSNotification*)aNote
{
    [pollTimeField setIntValue: [model pollTime]];
}
- (void) actualDurationChanged:(NSNotification*)aNote
{
	[actualDurationField setIntValue: [model actualDuration]];
}

- (void) tempUnitsChanged:(NSNotification*)aNote
{
	[tempUnitsField setStringValue: [model tempUnits]==0?@"C":@"F"];
	[tempUnitsPU selectItemAtIndex: [model tempUnits]];
    [self updateButtons];
}

- (void) countUnitsChanged:(NSNotification*)aNote
{
	[countUnitsPU selectItemAtIndex: [model countUnits]]; 
	NSString* s = @"";
	if([model countUnits]==0)		s = @"Counts/Ft^3";
	else if([model countUnits]==1)	s = @"Counts/L";
    else if([model countUnits]==2)  s = @"Total Counts";
    else if([model countUnits]==3)  s = @"Counts/M^3";
	[unitsField setStringValue:s];
	[plotter0 setYLabel:s];
    [self updateButtons];
}

- (void) statusBitsChanged:(NSNotification*)aNote
{
	int bits = [model statusBits];
	[batteryStatusField setStringValue: (bits & 0x10) ? @"BAD":@"OK"];
	[sensorStatusField  setStringValue:	(bits & 0x20) ? @"BAD":@"OK"];
}

- (void) humidityChanged:(NSNotification*)aNote
{
	[humidityField setFloatValue: [model humidity]];
}

- (void) temperatureChanged:(NSNotification*)aNote
{
	[temperatureField setFloatValue: [model temperature]];
}

- (void) countAlarmLimitChanged:(NSNotification*)aNote
{
	if(!aNote){
		int i;
		for(i=0;i<8;i++){
			[[countAlarmLimitMatrix cellWithTag:i] setIntValue:[model countAlarmLimit:i]];
		}
	}
	else {
		int chan = [[[aNote userInfo] objectForKey:@"Channel"] intValue];
		if(chan<8){
			[[countAlarmLimitMatrix cellWithTag:chan] setIntValue:[model countAlarmLimit:chan]];
		}
	}
}

- (void) maxCountsChanged:(NSNotification*)aNote
{
	if(!aNote){
		int i;
		for(i=0;i<8;i++){
			[[maxCountsMatrix cellWithTag:i] setFloatValue:[model maxCounts:i]];
		}
	}
	else {
		int chan = [[[aNote userInfo] objectForKey:@"Channel"] intValue];
		if(chan<8){
			[[maxCountsMatrix cellWithTag:chan] setFloatValue:[model maxCounts:chan]];
		}
	}
}

- (void) scaleAction:(NSNotification*)aNotification
{
	if(aNotification == nil || [aNotification object] == [plotter0 xAxis]){
		[model setMiscAttributes:[(ORAxis*)[plotter0 xAxis]attributes] forKey:@"XAttributes0"];
	};
	
	if(aNotification == nil || [aNotification object] == [plotter0 yAxis]){
		[model setMiscAttributes:[(ORAxis*)[plotter0 yAxis]attributes] forKey:@"YAttributes0"];
	};
}

- (void) miscAttributesChanged:(NSNotification*)aNote
{
	
	NSString*				key = [[aNote userInfo] objectForKey:ORMiscAttributeKey];
	NSMutableDictionary* attrib = [model miscAttributesForKey:key];
	
	if(aNote == nil || [key isEqualToString:@"XAttributes0"]){
		if(aNote==nil)attrib = [model miscAttributesForKey:@"XAttributes0"];
		if(attrib){
			[(ORAxis*)[plotter0 xAxis] setAttributes:attrib];
			[plotter0 setNeedsDisplay:YES];
			[[plotter0 xAxis] setNeedsDisplay:YES];
		}
	}
	if(aNote == nil || [key isEqualToString:@"YAttributes0"]){
		if(aNote==nil)attrib = [model miscAttributesForKey:@"YAttributes0"];
		if(attrib){
			[(ORAxis*)[plotter0 yAxis] setAttributes:attrib];
			[plotter0 setNeedsDisplay:YES];
			[[plotter0 yAxis] setNeedsDisplay:YES];
		}
	}
}

- (void) updateTimePlot:(NSNotification*)aNote
{
	if(!aNote || ([aNote object] == [model timeRate:1])){
		[plotter0 setNeedsDisplay:YES];
	}
}

- (void) cycleStartedChanged:(NSNotification*)aNote
{	
	NSString* startDateString = [[model cycleStarted] stdDescription];
	
	if(startDateString && [model running]) [cycleStartedField setStringValue:startDateString];
	else [cycleStartedField setStringValue:@"---"];
}

- (void) cycleNumberChanged:(NSNotification*)aNote
{
	[cycleNumberField setIntValue: [model cycleNumber]];
}

- (void) runningChanged:(NSNotification*)aNote
{
	[self updateButtons];
    BOOL running  = [model running];
    BOOL holding  = [model holding];
    NSString* s = @"";
    if(running){
        if(holding)s = @"Holding";
        else s = @"Running";
    }
    else s = @"Idle";
    [cycleStateField setStringValue:s];
}

- (void) cycleDurationChanged:(NSNotification*)aNote
{
	[cycleDurationField setIntValue: [model cycleDuration]];
}

- (void) numSamplesChanged:(NSNotification*)aNote
{
	//countingModePU and numSamplesField are the SAME popup: select the mode item ONCE.
	//(setIntValue: on a popup whose items both have tag 0 fights selectItemAtIndex: and
	//caused the mode to flip back.) numSamples==0 -> Repeat (0), else Single (1).
	[countingModePU selectItemAtIndex: [model numSamples]==0 ? 0 : 1];
}

- (void) countChanged:(NSNotification*)aNote
{
	int i;
	for(i=0;i<6;i++){
		[[countMatrix cellAtRow:i column:0] setIntValue:[model count:i]];
	}
}

- (void) checkGlobalSecurity
{
    BOOL secure = [[[NSUserDefaults standardUserDefaults] objectForKey:OROrcaSecurityEnabled] boolValue];
    [gSecurity setLock:ORBt610Lock to:secure];
    [lockButton setEnabled:secure];
}

- (void) lockChanged:(NSNotification*)aNotification
{
	[self updateButtons];
}

- (void) updateButtons
{
    BOOL locked = [gSecurity isLocked:ORBt610Lock];
	
	[serialPortController updateButtons:locked];

    [lockButton setState: locked];
    
	if(!locked){
		[startCycleButton setEnabled:![model running]];
		[stopCycleButton setEnabled:[model running]];
	}
	else {
		[startCycleButton setEnabled:NO];
		[stopCycleButton setEnabled:NO];
	}
    [holdTimeField setEnabled:![model running] && !locked];
	[cycleDurationField setEnabled:![model running] && !locked];
	[numSamplesField setEnabled:![model running] && !locked];
	[countingModePU setEnabled:![model running] && !locked];
	[countUnitsPU setEnabled:![model running] && !locked];
	[tempUnitsPU setEnabled:![model running] && !locked];
	[clearAllButton setEnabled:![model running] && !locked];
	[dumpAllButton setEnabled:![model running]];
	[dumpRecentButton setEnabled:![model running]];
	[loadSettingsButton setEnabled:![model running] && !locked]; //writes to device: idle only
	[syncSettingsButton setEnabled:!locked];                     //reads from device: anytime

}

- (void)tabView:(NSTabView *)aTabView didSelectTabViewItem:(NSTabViewItem *)tabViewItem
{
    [[self window] setContentView:blankView];
	NSUInteger style = [[self window] styleMask];
	switch([tabView indexOfTabViewItem:tabViewItem]){
		case  0: 
			[self resizeWindowToSize:basicOpsSize];   
			[[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
			break;
		case  1: 
			[self resizeWindowToSize:processOpsSize];     
			[[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
			break;
		case  2: 
			[self resizeWindowToSize:historyOpsSize];	
			[[self window] setStyleMask: style | NSWindowStyleMaskResizable];
			break;
		default: 
			[self resizeWindowToSize:basicOpsSize];
			[[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
			break;
	}
    [[self window] setContentView:totalView];
	
    NSString* key = [NSString stringWithFormat: @"orca.ORBt610%u.selectedtab",[model uniqueIdNumber]];
    NSInteger index = [tabView indexOfTabViewItem:tabViewItem];
    [[NSUserDefaults standardUserDefaults] setInteger:index forKey:key];
}

- (void)windowDidResize:(NSNotification *)notification
{
	if([tabView indexOfTabViewItem:[tabView selectedTabViewItem]] == 2){
		historyOpsSize = [[self window] frame].size; 
	}
}

#pragma mark ***Actions

- (void) isLogAction:(id)sender
{
	[model setIsLog:[sender intValue]];
}

- (IBAction) verboseAction:(id)sender
{
	[model setVerbose:[sender intValue]];
}

- (void) holdTimeAction:(id)sender
{
	[model setHoldTime:[sender intValue]];	
}

- (void) pollTimeAction:(id)sender
{
    [model setPollTime:[sender intValue]];
}

- (IBAction) numSamplesAction:(id)sender
{
	[model setNumSamples:[sender intValue]];
    //[self updateButtons];
}

//Counting mode popup: index 0 = Repeating (SN 0), index 1 = Single (SN n).
//Only updates ORCA; the SN command is sent to the machine via Load Settings.
- (IBAction) countingModeAction:(id)sender
{
	if([sender indexOfSelectedItem] == 0){
		[model setNumSamples:0];               //Repeating
	}
	else if([model numSamples] == 0){
		[model setNumSamples:1];               //switch to Single: default to 1 sample
	}
	[self updateButtons];
}

//Advanced Setting: take the (editable) channel sizes from the matrix and write them to the
//machine via the CS command.
- (IBAction) setChannelSizesAction:(id)sender
{
	[self endEditing];   //commit any in-progress cell edit
	[channelSizeEditMatrix validateEditing];   //flush the active field editor into the cell
	NSArray* editCells = [channelSizeEditMatrix cells];
	NSLog(@"Bt610: channelSizeEditMatrix rows=%ld cols=%ld cellCount=%lu\n",
		  (long)[channelSizeEditMatrix numberOfRows],(long)[channelSizeEditMatrix numberOfColumns],(unsigned long)[editCells count]);
	int i;
	for(i=0;i<6 && i<(int)[editCells count];i++){
		NSString* sz = [[[editCells objectAtIndex:i] stringValue]
						stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
		NSLog(@"Bt610:   editCell[%d] = '%@'\n",i,sz);
		[model setChannelSize:i value:sz];
	}
	[model sendChannelSizes];   //CS command
}

- (IBAction) tempUnitsAction:(id)sender
{
	//only update ORCA; the machine is written only via the Load Settings button
	[model setTempUnits:(int)[sender indexOfSelectedItem]];
}
/*
- (IBAction) countAlarmLimitAction:(id)sender
{
	[model setIndex:(int)[[sender selectedCell] tag] countAlarmLimit:[[sender selectedCell] floatValue]];	
}

- (IBAction) maxCountsAction:(id)sender
{
	[model setIndex:(int)[[sender selectedCell] tag] maxCounts:[[sender selectedCell] floatValue]];
}
*/
- (IBAction) countAlarmLimitAction:(id)sender
{
    int value = [self digitsOnlyValue:[[sender selectedCell] stringValue]];
    [model setIndex:(int)[[sender selectedCell] tag] countAlarmLimit:(float)value];
}

- (IBAction) maxCountsAction:(id)sender
{
    int value = [self digitsOnlyValue:[[sender selectedCell] stringValue]];
    [model setIndex:(int)[[sender selectedCell] tag] maxCounts:(float)value];
}

//strip any grouping separators (comma, space, non-breaking space, etc.) so the
//value parses correctly regardless of the user's macOS Region/locale settings
- (int) digitsOnlyValue:(NSString*)aString
{
    NSCharacterSet* nonDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
    NSString* digits = [[aString componentsSeparatedByCharactersInSet:nonDigits] componentsJoinedByString:@""];
    return [digits intValue];
}


- (IBAction) startCycleAction:(id)sender
{
	[self endEditing];
    [model setMissedCycleCount:0];
	[model startCycle];	
}

- (IBAction) stopCycleAction:(id)sender
{
	[self endEditing];
    [model setMissedCycleCount:0];
	[model stopCycle];	
}

- (IBAction) cycleDurationAction:(id)sender
{
	[model setCycleDuration:[sender intValue]];	
}

- (IBAction) lockAction:(id) sender
{
    [gSecurity tryToSetLock:ORBt610Lock to:[sender intValue] forWindow:[self window]];
}

- (IBAction) countUnitsAction:(id)sender
{
	//only update ORCA; the machine is written only via the Load Settings button
	[model setCountUnits:(int)[sender indexOfSelectedItem]];
}

- (IBAction) readSerialNumberAction:(id)sender
{
	[model getSerialNumber]; //sends SS; reply updates serialNumberField
}

- (IBAction) readSoftwareVersionAction:(id)sender
{
	[model getSoftwareVersion]; //sends RV; reply updates softwareVersionField
}

- (IBAction) probeModelAction:(id)sender
{
	//queries serial #, software version, and all settings, then prints a summary to the log
	[model probeModel];
}

//Load Settings: push ORCA's configured settings out to the machine
- (IBAction) loadSettingsAction:(id)sender
{
	[self endEditing];
	[model writeSettingsToDevice];
}

//Sync Settings: pull the machine's current settings back into ORCA
- (IBAction) syncSettingsAction:(id)sender
{
	[model readSettingsFromDevice];
	//[model getSerialNumber];
}

- (IBAction) dumpAllDataAction:(id)sender
{
	[model sendAllData];
}

- (IBAction) dumpNewDataAction:(id)sender
{
	[model sendNewData];
}


- (IBAction) clearAllAction:(id)sender
{
#if defined(MAC_OS_X_VERSION_10_10) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_10 // 10.10-specific
    NSAlert *alert = [[[NSAlert alloc] init] autorelease];
    [alert setMessageText:@"Clearing all data!"];
    [alert setInformativeText:@"Is this really what you want?"];
    [alert addButtonWithTitle:@"Yes, Clear All"];
    [alert addButtonWithTitle:@"Cancel"];
    [alert setAlertStyle:NSAlertStyleWarning];
    
    [alert beginSheetModalForWindow:[self window] completionHandler:^(NSModalResponse result){
        if (result == NSAlertFirstButtonReturn){
            [model sendClearData];
        }
    }];
#else
    NSBeginAlertSheet(@"Clearing all data!",
                      @"Cancel",
                      @"Yes, Clear All",
                      nil,[self window],
                      self,
                      @selector(clearDataSheetDidEnd:returnCode:contextInfo:),
                      nil,
                      nil,@"Is this really what you want?");
#endif
}

#if !defined(MAC_OS_X_VERSION_10_10) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_10 // 10.10-specific
- (void) clearDataSheetDidEnd:(id)sheet returnCode:(int)returnCode contextInfo:(NSDictionary*)userInfo
{
    if(returnCode == NSAlertAlternateReturn){
		[model sendClearData];	
	}
}
#endif
#pragma mark •••Data Source
- (int) numberPointsInPlot:(id)aPlotter
{
	return (int)[[model timeRate:(int)[aPlotter tag]]   count];
}

- (void) plotter:(id)aPlotter index:(int)i x:(double*)xValue y:(double*)yValue
{
	int set = (int)[aPlotter tag];
	int count = (int)[[model timeRate:set] count];
	int index = count-i-1;
	*yValue = [[model timeRate:set] valueAtIndex:index];
	*xValue = [[model timeRate:set] timeSampledAtIndex:index];
}

@end

