//--------------------------------------------------------
// ORPMS31Controller
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

@class ORCompositeTimeLineView;
@class ORSerialPortController;

@interface ORPMS31Controller : OrcaObjectController
{
    IBOutlet NSTabView*         tabView;    
    IBOutlet NSView*            totalView;
    IBOutlet NSTextField*       lockDocField;
    IBOutlet NSTextField*       timedOutField;
    IBOutlet NSButton*          isLogCB;

    IBOutlet NSTextField*       slaveAddressField;
    IBOutlet NSPopUpButton*     baudRatePU;
    IBOutlet NSTextField*       pollIntervalField;
    IBOutlet NSPopUpButton*     countingModePU;
    IBOutlet NSPopUpButton*     deviceCountModePU;
    IBOutlet NSPopUpButton*     deviceSampleUnitModePU;
    
    IBOutlet NSMatrix*          countMatrix;
    IBOutlet NSTextField*       measurementDateField;

    IBOutlet NSButton*          lockButton;
    IBOutlet NSTextField*       cycleDurationField;
    IBOutlet NSTextField*       holdDurationField;
    IBOutlet NSButton*          startCycleButton;
    IBOutlet NSButton*          stopCycleButton;
    IBOutlet NSTextField*       cycleNumberField;
    IBOutlet NSTextField*       cycleWillEndField;
    IBOutlet NSTextField*       cycleStartedField;
    IBOutlet NSTextField*       runningField;
    
    IBOutlet ORCompositeTimeLineView*   plotter0;
    IBOutlet NSMatrix* countAlarmLimitMatrix;
    IBOutlet NSMatrix* maxCountsMatrix;

    // Summary tab duplicates
    IBOutlet NSMatrix*          count2Matrix;
    IBOutlet NSTextField*       measurementDate2Field;
    IBOutlet NSTextField*       cycleWillEnd2Field;
    IBOutlet NSTextField*       running2Field;
    
    IBOutlet ORSerialPortController* serialPortController;

    NSSize                      basicOpsSize;
    NSSize                      processOpsSize;
    NSSize                      summaryOpsSize;
    NSSize                      historyOpsSize;
    NSView*                     blankView;
    
}

#pragma mark ***Initialization
- (id) init;
- (void) dealloc;
- (void) awakeFromNib;

#pragma mark ***Notifications
- (void) registerNotificationObservers;
- (void) updateWindow;

#pragma mark ***Interface Management
- (void) timedOutChanged:(NSNotification*)aNote;
- (void) isLogChanged:(NSNotification*)aNote;
- (void) slaveAddressChanged:(NSNotification*)aNote;
- (void) baudRateChanged:(NSNotification*)aNote;
- (void) pollIntervalChanged:(NSNotification*)aNote;
- (void) deviceCountModeChanged:(NSNotification*)aNote;
- (void) deviceSampleUnitModeChanged:(NSNotification *)aNote;
- (void) countAlarmLimitChanged:(NSNotification*)aNote;
- (void) maxCountsChanged:(NSNotification*)aNote;
- (void) cycleNumberChanged:(NSNotification*)aNote;
- (void) cycleWillEndChanged:(NSNotification*)aNote;
- (void) cycleStartedChanged:(NSNotification*)aNote;
- (void) runningChanged:(NSNotification*)aNote;
- (void) cycleDurationChanged:(NSNotification*)aNote;
- (void) holdDurationChanged:(NSNotification*)aNote;
- (void) countingModeChanged:(NSNotification*)aNote;
- (void) countChanged:(NSNotification*)aNote;
- (void) measurementDateChanged:(NSNotification*)aNote;
- (void) updateButtons;
- (void) lockChanged:(NSNotification*)aNote;
- (void) updateTimePlot:(NSNotification*)aNote;
- (void) scaleAction:(NSNotification*)aNote;
- (void) miscAttributesChanged:(NSNotification*)aNote;
- (void) tabView:(NSTabView *)aTabView didSelectTabViewItem:(NSTabViewItem *)tabViewItem;
- (void) windowDidResize:(NSNotification *)aNote;

#pragma mark ***Actions
- (IBAction) isLogAction:(id)sender;
- (IBAction) slaveAddressAction:(id)sender;
- (IBAction) baudRateAction:(id)sender;
- (IBAction) pollIntervalAction:(id)sender;
- (IBAction) deviceCountModeAction:(id)sender;
- (IBAction) deviceSampleUnitModeAction:(id)sender;
- (IBAction) countAlarmLimitAction:(id)sender;
- (IBAction) maxCountsAction:(id)sender;
- (IBAction) lockAction:(id) sender;
- (IBAction) cycleDurationAction:(id)sender;
- (IBAction) holdDurationAction:(id)sender;
- (IBAction) startCycleAction:(id)sender;
- (IBAction) stopCycleAction:(id)sender;
- (IBAction) countingModeAction:(id)sender;

#pragma mark ***Data Source
- (int) numberPointsInPlot:(id)aPlotter;
- (void) plotter:(id)aPlotter index:(int)i x:(double*)xValue y:(double*)yValue;
@end
