
//--------------------------------------------------------
// ORPMS31Model
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

#import "ORPMS31Model.h"
#import "ORSerialPortAdditions.h"
#import "ORDataTypeAssigner.h"
#import "ORDataPacket.h"
#import "ORTimeRate.h"
#import "ORAlarm.h"

#pragma mark ***External Strings
NSString* ORPMS31ModelIsLogChanged            = @"ORPMS31ModelIsLogChanged";
NSString* ORPMS31ModelLocationChanged         = @"ORPMS31ModelLocationChanged";
NSString* ORPMS31ModelCountAlarmLimitChanged   = @"ORPMS31ModelCountAlarmLimitChanged";
NSString* ORPMS31ModelMaxCountsChanged        = @"ORPMS31ModelMaxCountsChanged";
NSString* ORPMS31ModelCycleNumberChanged      = @"ORPMS31ModelCycleNumberChanged";
NSString* ORPMS31ModelCycleWillEndChanged     = @"ORPMS31ModelCycleWillEndChanged";
NSString* ORPMS31ModelCycleStartedChanged     = @"ORPMS31ModelCycleStartedChanged";
NSString* ORPMS31ModelRunningChanged          = @"ORPMS31ModelRunningChanged";
NSString* ORPMS31ModelCycleDurationChanged    = @"ORPMS31ModelCycleDurationChanged";
NSString* ORPMS31ModelCountingModeChanged     = @"ORPMS31ModelCountingModeChanged";
NSString* ORPMS31ModelCountChanged            = @"ORPMS31ModelCountChanged";
NSString* ORPMS31ModelMeasurementDateChanged  = @"ORPMS31ModelMeasurementDateChanged";
NSString* ORPMS31ModelMissedCountChanged      = @"ORPMS31ModelMissedCountChanged";
NSString* ORPMS31ModelSlaveAddressChanged     = @"ORPMS31ModelSlaveAddressChanged";
NSString* ORPMS31ModelBaudRateChanged         = @"ORPMS31ModelBaudRateChanged";
NSString* ORPMS31ModelPollIntervalChanged     = @"ORPMS31ModelPollIntervalChanged";
NSString* ORPMS31ModelDeviceCountModeChanged  = @"ORPMS31ModelDeviceCountModeChanged";
NSString* ORPMS31ModelDeviceSampleUnitChanged = @"ORPMS31ModelDeviceSampleUnitChanged";
NSString* ORPMS31Lock = @"ORPMS31Lock";

@interface ORPMS31Model (private)
- (void) addCmdToQueue:(NSData*)aCmd;
- (void) processModbusResponse:(NSData*)responseData;
- (void) processOneCommandFromQueue;
- (void) pollOnce;
- (void) startPolling;
- (void) stopPolling;
- (void) startCycleTimer;
- (void) cancelCycleTimer;
- (void) cycleComplete;
- (void) startDataArrivalTimeout;
- (void) cancelDataArrivalTimeout;
- (void) doCycleKick;
- (void) postCouchDBRecord;
@end

@implementation ORPMS31Model

- (id) init
{
    self = [super init];
    [[self undoManager] disableUndoRegistration];
    slaveAddress  = kPMS31DefaultSlaveAddr;
    baudRate      = kPMS31DefaultBaudRate;
    pollInterval  = kPMS31DefaultPollInterval;
    cycleDuration = 60;
    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [self setIndex:i maxCounts:1000];
        [self setIndex:i countAlarmLimit:800];
    }
    [[self undoManager] enableUndoRegistration];
    [self startPolling];
    return self;
}

- (void) dealloc
{
    [cycleWillEnd release];
    [cycleStarted release];
    [measurementDate release];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [NSObject cancelPreviousPerformRequestsWithTarget:self];
    [dataBuffer release];
    
    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [timeRates[i] release];
    }
    
    [missingCyclesAlarm release];
    [missingCyclesAlarm clearAlarm];

    [super dealloc];
}

- (void) sleep
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self];
    [super sleep];
}

- (void) wakeUp
{
    [super wakeUp];
}

- (void) setUpImage
{
    [self setImage:[NSImage imageNamed:@"PMS_31.tif"]];
}

- (void) makeMainController
{
    [self linkToController:@"ORPMS31Controller"];
}

- (NSString*) helpURL
{
    return @"RS232/PMS31.html";
}

#pragma mark ***Data Received - Modbus Binary
- (void) dataReceived:(NSNotification*)note
{
    if([[note userInfo] objectForKey:@"serialPort"] == serialPort){
        NSData* theData = [[note userInfo] objectForKey:@"data"];
        
        if(!dataBuffer) dataBuffer = [[NSMutableData data] retain];
        [dataBuffer appendData:theData];
        
        // Check if we have enough bytes for a complete Modbus response
        if([dataBuffer length] < 3) return; // need at least addr + func + 1 byte
        
        unsigned char* bytes = (unsigned char*)[dataBuffer bytes];
        int len = (int)[dataBuffer length];
        
        // Check for Modbus error response (function code with bit 7 set)
        if(bytes[1] & 0x80){
            // Error response is always 5 bytes: addr + errFC + errCode + CRC(2)
            if(len >= 5){
                NSData* response = [NSData dataWithBytes:bytes length:5];
                [dataBuffer replaceBytesInRange:NSMakeRange(0, 5) withBytes:NULL length:0];
                [self processModbusResponse:response];
            }
            return;
        }
        
        // Determine expected response length based on function code
        int neededLength = 0;
        unsigned char funcCode = bytes[1];
        
        if(funcCode == kPMS31FC_ReadInputReg || funcCode == kPMS31FC_ReadHoldingReg){
            // Response: addr(1) + fc(1) + byteCount(1) + data(N) + crc(2)
            if(len >= 3){
                int byteCount = bytes[2];
                neededLength = 3 + byteCount + 2;
            }
        }
        else if(funcCode == kPMS31FC_WriteSingleReg){
            // Echo response: addr(1) + fc(1) + reg(2) + value(2) + crc(2) = 8
            neededLength = 8;
        }
        else if(funcCode == kPMS31FC_WriteMultiReg){
            // Response: addr(1) + fc(1) + startReg(2) + numRegs(2) + crc(2) = 8
            neededLength = 8;
        }
        
        if(neededLength > 0 && len >= neededLength){
            NSData* response = [NSData dataWithBytes:bytes length:neededLength];
            [dataBuffer replaceBytesInRange:NSMakeRange(0, neededLength) withBytes:NULL length:0];
            [self processModbusResponse:response];
        }
    }
}

#pragma mark ***Accessors

- (int) slaveAddress
{
    return slaveAddress;
}

- (void) setSlaveAddress:(int)aSlaveAddress
{
    if(aSlaveAddress < 1) aSlaveAddress = 1;
    if(aSlaveAddress > 0xFE) aSlaveAddress = 0xFE;
    [[[self undoManager] prepareWithInvocationTarget:self] setSlaveAddress:slaveAddress];
    slaveAddress = aSlaveAddress;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelSlaveAddressChanged object:self];
}

- (int) baudRate
{
    return baudRate;
}

- (void) setBaudRate:(int)aBaudRate
{
    [[[self undoManager] prepareWithInvocationTarget:self] setBaudRate:baudRate];
    baudRate = aBaudRate;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelBaudRateChanged object:self];
}

- (int) pollInterval
{
    return pollInterval;
}

- (void) setPollInterval:(int)aPollInterval
{
    if(aPollInterval < 1) aPollInterval = 1;
    if(aPollInterval > 300) aPollInterval = 300;
    [[[self undoManager] prepareWithInvocationTarget:self] setPollInterval:pollInterval];
    pollInterval = aPollInterval;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelPollIntervalChanged object:self];
}

- (int) deviceCountMode
{
    return deviceCountMode;
}
- (int) deviceSampleUnit
{
    return deviceSampleUnit;
}

- (void) setDeviceCountMode:(int)aMode
{
    if(aMode < 0) aMode = 0;
    if(aMode > 1) aMode = 1;
    [[[self undoManager] prepareWithInvocationTarget:self] setDeviceCountMode:deviceCountMode];
    deviceCountMode = aMode;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelDeviceCountModeChanged object:self];
}

- (void) setDeviceSampleUnit:(int)aUnit
{
    if (aUnit<0) aUnit = 0;
    if (aUnit>3) aUnit = 3;
    [[[self undoManager] prepareWithInvocationTarget:self] setDeviceSampleUnit:deviceSampleUnit];
    deviceSampleUnit = aUnit;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelDeviceSampleUnitChanged object:self];
}


- (int) missedCycleCount
{
    return missedCycleCount;
}

- (void) setMissedCycleCount:(int)aValue
{
    missedCycleCount = aValue;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelMissedCountChanged object:self];
    
    if(((missedCycleCount >= 3) && (countingMode == kPMS31Auto)) || 
       ((missedCycleCount > 0) && (countingMode == kPMS31Manual))){
        if(!missingCyclesAlarm){
            NSString* s = [NSString stringWithFormat:@"PMS31 (Unit %u) Missing Cycles",[self uniqueIdNumber]];
            missingCyclesAlarm = [[ORAlarm alloc] initWithName:s severity:kHardwareAlarm];
            [missingCyclesAlarm setSticky:YES];
            if(countingMode == kPMS31Manual){
                [missingCyclesAlarm setHelpString:@"The PMS31 particle counter did not report counts at the end of its last single cycle.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
            }
            else {
                [missingCyclesAlarm setHelpString:@"The PMS31 particle counter is not reporting counts at the end of its cycle. ORCA tried to kick start it at least three times.\n\nThis alarm will not go away until the problem is cleared. Acknowledging the alarm will silence it."];
            }
            [missingCyclesAlarm postAlarm];
        }
    }
    else {
        [missingCyclesAlarm clearAlarm];
        [missingCyclesAlarm release];
        missingCyclesAlarm = nil;
    }
}

- (BOOL) isLog
{
    return isLog;
}

- (void) setIsLog:(BOOL)aIsLog
{
    [[[self undoManager] prepareWithInvocationTarget:self] setIsLog:isLog];
    isLog = aIsLog;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelIsLogChanged object:self];
}

- (int) location
{
    return location;
}

- (void) setLocation:(int)aLocation
{
    [[[self undoManager] prepareWithInvocationTarget:self] setLocation:location];
    location = aLocation;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelLocationChanged object:self];
}

- (float) countAlarmLimit:(int)index
{
    if(index>=0 && index<kPMS31NumChannels) return countAlarmLimit[index];
    else return 0;
}

- (void) setIndex:(int)index countAlarmLimit:(float)aCountAlarmLimit
{
    if(index<0 || index>=kPMS31NumChannels)return;
    [[[self undoManager] prepareWithInvocationTarget:self] setIndex:index countAlarmLimit:countAlarmLimit[index]];
    countAlarmLimit[index] = aCountAlarmLimit;
    NSMutableDictionary* userInfo = [NSMutableDictionary dictionary];
    [userInfo setObject:[NSNumber numberWithInt:index] forKey: @"Channel"];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCountAlarmLimitChanged object:self userInfo:userInfo];
}

- (float) maxCounts:(int)index
{
    if(index>=0 && index<kPMS31NumChannels) return maxCounts[index];
    else return 0;
}

- (void) setIndex:(int)index maxCounts:(float)aMaxCounts
{
    if(index<0 || index>=kPMS31NumChannels)return;
    [[[self undoManager] prepareWithInvocationTarget:self] setIndex:index maxCounts:maxCounts[index]];
    maxCounts[index] = aMaxCounts;
    NSMutableDictionary* userInfo = [NSMutableDictionary dictionary];
    [userInfo setObject:[NSNumber numberWithInt:index] forKey: @"Channel"];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelMaxCountsChanged object:self  userInfo:userInfo];
}

- (ORTimeRate*)timeRate:(int)index
{
    if(index>=0 && index<kPMS31NumChannels) return timeRates[index];
    else return nil;
}

- (int) cycleNumber
{
    return cycleNumber;
}

- (void) setCycleNumber:(int)aCycleNumber
{
    cycleNumber = aCycleNumber;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCycleNumberChanged object:self];
}

- (NSDate*) cycleWillEnd
{
    return cycleWillEnd;
}

- (void) setCycleWillEnd:(NSDate*)aCycleWillEnd
{
    [aCycleWillEnd retain];
    [cycleWillEnd release];
    cycleWillEnd = aCycleWillEnd;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCycleWillEndChanged object:self];
}

- (NSDate*) cycleStarted
{
    return cycleStarted;
}

- (void) setCycleStarted:(NSDate*)aCycleStarted
{
    [aCycleStarted retain];
    [cycleStarted release];
    cycleStarted = aCycleStarted;

    int totalTime = [self cycleDuration];
    NSDate* endTime = [aCycleStarted dateByAddingTimeInterval:totalTime];
    [self setCycleWillEnd:endTime]; 
    
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCycleStartedChanged object:self];
}

- (BOOL) running
{
    return running;
}

- (void) setRunning:(BOOL)aRunning
{
    running = aRunning;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelRunningChanged object:self];
}

- (int) cycleDuration
{
    return cycleDuration;
}

- (void) setCycleDuration:(int)aCycleDuration
{
    if(aCycleDuration < 10) aCycleDuration = 10;
    else if(aCycleDuration > 9999) aCycleDuration = 9999;
    [[[self undoManager] prepareWithInvocationTarget:self] setCycleDuration:cycleDuration];
    cycleDuration = aCycleDuration;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCycleDurationChanged object:self];
}

- (int) countingMode
{
    return countingMode;
}

- (void) setCountingMode:(int)aCountingMode
{
    countingMode = aCountingMode;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCountingModeChanged object:self];
}

- (NSString*) countingModeString
{
    switch ([self countingMode]) {
        case kPMS31Manual: return @"Single Cycle";
        case kPMS31Auto:   return @"Repeating";
        default: return @"--";
    }
}

- (void) setCount:(int)index value:(int)aValue
{
    if(index>=0 && index<kPMS31NumChannels){
        count[index] = aValue;
        [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelCountChanged object:self];
        if(timeRates[index] == nil) timeRates[index] = [[ORTimeRate alloc] init];
        [timeRates[index] addDataToTimeAverage:aValue];
    }
}

- (int) count:(int)index
{
    if(index>=0 && index<kPMS31NumChannels)return count[index];
    else return 0;
}

- (NSString*) measurementDate
{
    if(!measurementDate)return @"";
    else return measurementDate;
}

- (void) setMeasurementDate:(NSString*)aMeasurementDate
{
    [measurementDate autorelease];
    measurementDate = [aMeasurementDate copy];    
    [[NSNotificationCenter defaultCenter] postNotificationName:ORPMS31ModelMeasurementDateChanged object:self];
}

- (void) setUpPort
{
    [serialPort setSpeed:baudRate];
    [serialPort setParityNone];
    [serialPort setStopBits2:NO];
    [serialPort setDataBits:8];
}

- (void) firstActionAfterOpeningPort
{
    // Read particle counts once to verify communication
    [self readParticleCounts];
}

#pragma mark ***Archival
- (id) initWithCoder:(NSCoder*)decoder
{
    self = [super initWithCoder:decoder];
    [[self undoManager] disableUndoRegistration];
    [self setIsLog:         [decoder decodeBoolForKey:@"isLog"]];
    [self setLocation:      [decoder decodeIntForKey:   @"location"]];
    wasRunning =            [decoder decodeBoolForKey:  @"wasRunning"];
    [self setCycleDuration: [decoder decodeIntForKey:   @"cycleDuration"]];
    [self setCountingMode:  [decoder decodeIntForKey:   @"countingMode"]];
    [self setSlaveAddress:  [decoder decodeIntForKey:   @"slaveAddress"]];
    [self setBaudRate:      [decoder decodeIntForKey:   @"baudRate"]];
    [self setPollInterval:  [decoder decodeIntForKey:   @"pollInterval"]];
    [self setDeviceCountMode:[decoder decodeIntForKey: @"deviceCountMode"]];
    [self setDeviceSampleUnit:[decoder decodeIntForKey: @"deviceSampleUnit"]];
    if(slaveAddress == 0) slaveAddress = kPMS31DefaultSlaveAddr;
    if(baudRate == 0)     baudRate = kPMS31DefaultBaudRate;
    if(pollInterval == 0) pollInterval = kPMS31DefaultPollInterval;

    int i; 
    for(i=0;i<kPMS31NumChannels;i++){
        timeRates[i] = [[ORTimeRate alloc] init];
        [self setIndex:i countAlarmLimit:   [decoder decodeFloatForKey: [NSString stringWithFormat:@"countAlarmLimit%d",i]]];
        [self setIndex:i maxCounts:         [decoder decodeFloatForKey: [NSString stringWithFormat:@"maxCounts%d",i]]];
    }
    
    [[self undoManager] enableUndoRegistration];
    return self;
}

- (void) encodeWithCoder:(NSCoder*)encoder
{
    [super encodeWithCoder:encoder];
    [encoder encodeBool:    isLog           forKey:@"isLog"];
    [encoder encodeInteger: location        forKey: @"location"];
    [encoder encodeInteger: cycleDuration   forKey: @"cycleDuration"];
    [encoder encodeInteger: countingMode    forKey: @"countingMode"];
    [encoder encodeBool:    wasRunning      forKey: @"wasRunning"];
    [encoder encodeInteger: slaveAddress    forKey: @"slaveAddress"];
    [encoder encodeInteger: baudRate        forKey: @"baudRate"];
    [encoder encodeInteger: pollInterval      forKey: @"pollInterval"];
    [encoder encodeInteger: deviceCountMode  forKey: @"deviceCountMode"];
    [encoder encodeInteger: deviceSampleUnit  forKey: @"deviceSampleUnit"];
    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [encoder encodeFloat:   countAlarmLimit[i] forKey: [NSString stringWithFormat:@"countAlarmLimit%d",i]];
        [encoder encodeFloat:   maxCounts[i]       forKey: [NSString stringWithFormat:@"maxCounts%d",i]];
    }
}

#pragma mark ***Modbus Helpers

- (unsigned int) modbusCalcCRC:(unsigned char*)mess length:(int)cnt
{
    unsigned short crc = 0xFFFF;
    int i;
    for(i = 0; i < cnt; i++){
        crc = crc ^ mess[i];
        int shift;
        for(shift = 1; shift <= 8; shift++){
            unsigned char lastbit = crc & 0x0001;
            crc = crc >> 1;
            if(lastbit == 1) crc = crc ^ 0xA001;
        }
    }
    return crc;
}

- (NSData*) buildReadInputRegistersFrame:(int)startReg count:(int)regCount
{
    NSMutableData* frame = [NSMutableData dataWithLength:8];
    unsigned char* bytes = (unsigned char*)[frame mutableBytes];
    
    bytes[0] = (unsigned char)slaveAddress;
    bytes[1] = kPMS31FC_ReadInputReg;
    bytes[2] = (startReg >> 8) & 0xFF;
    bytes[3] = startReg & 0xFF;
    bytes[4] = (regCount >> 8) & 0xFF;
    bytes[5] = regCount & 0xFF;
    
    unsigned int crc = [self modbusCalcCRC:bytes length:6];
    bytes[6] = crc & 0xFF;        // CRC low byte first
    bytes[7] = (crc >> 8) & 0xFF; // CRC high byte
    
    return frame;
}

- (NSData*) buildWriteSingleRegisterFrame:(int)reg value:(int)value
{
    NSMutableData* frame = [NSMutableData dataWithLength:8];
    unsigned char* bytes = (unsigned char*)[frame mutableBytes];
    
    bytes[0] = (unsigned char)slaveAddress;
    bytes[1] = kPMS31FC_WriteSingleReg;
    bytes[2] = (reg >> 8) & 0xFF;
    bytes[3] = reg & 0xFF;
    bytes[4] = (value >> 8) & 0xFF;
    bytes[5] = value & 0xFF;
    
    unsigned int crc = [self modbusCalcCRC:bytes length:6];
    bytes[6] = crc & 0xFF;
    bytes[7] = (crc >> 8) & 0xFF;
    
    return frame;
}

- (NSData*) buildWriteMultipleRegistersFrame:(int)startReg values:(int*)values count:(int)regCount
{
    int byteCount = regCount * 2;
    int frameLength = 7 + byteCount + 2; // addr(1)+fc(1)+startReg(2)+numRegs(2)+byteCount(1)+data(N)+crc(2)
    NSMutableData* frame = [NSMutableData dataWithLength:frameLength];
    unsigned char* bytes = (unsigned char*)[frame mutableBytes];
    
    bytes[0] = (unsigned char)slaveAddress;
    bytes[1] = kPMS31FC_WriteMultiReg;
    bytes[2] = (startReg >> 8) & 0xFF;
    bytes[3] = startReg & 0xFF;
    bytes[4] = (regCount >> 8) & 0xFF;
    bytes[5] = regCount & 0xFF;
    bytes[6] = (unsigned char)byteCount;
    
    int i;
    for(i = 0; i < regCount; i++){
        bytes[7 + i*2]     = (values[i] >> 8) & 0xFF;
        bytes[7 + i*2 + 1] = values[i] & 0xFF;
    }
    
    int dataLen = 7 + byteCount;
    unsigned int crc = [self modbusCalcCRC:bytes length:dataLen];
    bytes[dataLen]     = crc & 0xFF;
    bytes[dataLen + 1] = (crc >> 8) & 0xFF;
    
    return frame;
}

#pragma mark ***Modbus Commands

- (void) readParticleCounts
{
    if([serialPort isOpen]){
        NSData* frame = [self buildReadInputRegistersFrame:kPMS31Reg_CountsStart count:kPMS31Reg_CountsCount];
        [self addCmdToQueue:frame];
    }
}

- (void) startDetection
{
    if([serialPort isOpen]){
        NSData* frame = [self buildWriteSingleRegisterFrame:kPMS31Reg_StartStop value:0x0001];
        [self addCmdToQueue:frame];
    }
}

- (void) stopDetection
{
    if([serialPort isOpen]){
        NSData* frame = [self buildWriteSingleRegisterFrame:kPMS31Reg_StartStop value:0x0000];
        [self addCmdToQueue:frame];
    }
}

- (void) syncDeviceTime
{
    if([serialPort isOpen]){
        unsigned unitFlags = NSCalendarUnitYear | NSCalendarUnitMonth |  NSCalendarUnitDay | NSCalendarUnitMinute | NSCalendarUnitHour | NSCalendarUnitSecond;
        NSDate *today = [NSDate date];
        NSCalendar *gregorian = [[[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian] autorelease];
        NSDateComponents *comps = [gregorian components:unitFlags fromDate:today];
        
        int timeValues[6];
        timeValues[0] = (int)[comps year];
        timeValues[1] = (int)[comps month];
        timeValues[2] = (int)[comps day];
        timeValues[3] = (int)[comps hour];
        timeValues[4] = (int)[comps minute];
        timeValues[5] = (int)[comps second];
        
        NSData* frame = [self buildWriteMultipleRegistersFrame:kPMS31Reg_TimeStart values:timeValues count:kPMS31Reg_TimeCount];
        [self addCmdToQueue:frame];
    }
}

- (void) sendDeviceCountMode
{
    if([serialPort isOpen]){
        // Write to register 0x0E: 0x00=Sum(cumulative), 0x01=Diff(differential)
        NSData* frame = [self buildWriteSingleRegisterFrame:kPMS31Reg_CountMode value:deviceCountMode];
        [self addCmdToQueue:frame];
        NSLog(@"PMS31(%d): Sending device count mode = %@ (0x%02X)\n",
              [self uniqueIdNumber], deviceCountMode == kPMS31CountModeDiff ? @"Diff" : @"Sum", deviceCountMode);
    }
}

- (void) sendDeviceUnitMode
{
    if([serialPort isOpen]){
        NSData* frame = [self buildWriteSingleRegisterFrame:kPMS31Reg_SampleUnit value:deviceSampleUnit];
        [self addCmdToQueue:frame];
    }
}
#pragma mark ***Polling and Cycles

- (void) startCycle
{
    [self startCycle:NO];
}

- (void) startCycle:(BOOL)force
{
    if((![self running] || force) && [serialPort isOpen]){
        [self setCycleNumber:1];
        int i;
        for(i=0;i<kPMS31NumChannels;i++){
            [self setCount:i value:0];
        }
        NSDate* now = [NSDate date];
        [self setCycleStarted:now];
        [self sendDeviceCountMode];
        [self sendDeviceUnitMode];
        [self startDetection];
        [self setRunning:YES];
        [self startPolling];
        [self startCycleTimer];
        [self startDataArrivalTimeout];
        NSLog(@"PMS31(%d) Starting particle counter in %@ mode (cycle duration: %d sec)\n",[self uniqueIdNumber], [self countingModeString], cycleDuration);
    }
}

- (void) stopCycle
{
    //[self stopPolling];
    [self cancelCycleTimer];
    [self cancelDataArrivalTimeout];
    if([serialPort isOpen]){
        [self stopDetection];
    }
    [self setCycleNumber:0];
    [self setRunning:NO];
    NSLog(@"PMS31(%d) Stopping particle counter. Was in %@ mode\n",[self uniqueIdNumber], [self countingModeString]);
}


#pragma mark •••Adc Processing Protocol
- (void) processIsStarting
{
    if(!running){
        if(!sentStartOnce){
           sentStartOnce = YES;
           sentStopOnce = NO;
            wasRunning = NO;
            [self startCycle:YES];
        }
    }
    else wasRunning = YES;
}

- (void) processIsStopping
{
    if(!wasRunning){
        if(!sentStopOnce){
            sentStopOnce = YES;
            sentStartOnce = NO;
            [self stopCycle];
        }
    }
}

- (void) startProcessCycle
{    
    @try { 
    }
    @catch(NSException* localException) { 
    }
}

- (void) endProcessCycle
{
}

- (NSString*) identifier
{
    NSString* s;
    @synchronized(self){
        s= [NSString stringWithFormat:@"PMS31,%u",[self uniqueIdNumber]];
    }
    return s;
}

- (NSString*) processingTitle
{
    NSString* s;
    @synchronized(self){
        s= [self identifier];
    }
    return s;
}

- (double) convertedValue:(int)aChan
{
    double theValue = 0;
    @synchronized(self){
        if(aChan>=0 && aChan<kPMS31NumChannels) theValue = [self count:aChan];
    }
    return theValue;
}

- (double) maxValueForChan:(int)aChan
{
    double theValue;
    @synchronized(self){
        theValue = (double)[self maxCounts:aChan]; 
    }
    return theValue;
}

- (double) minValueForChan:(int)aChan
{
    return 0;
}

- (void) getAlarmRangeLow:(double*)theLowLimit high:(double*)theHighLimit channel:(int)channel
{
    @synchronized(self){
        *theLowLimit = -.001;
        *theHighLimit =  [self countAlarmLimit:channel]; 
    }        
}

- (BOOL) processValue:(int)channel
{
    BOOL r;
    @synchronized(self){
        r = YES;
    }
    return r;
}

- (void) setProcessOutput:(int)channel value:(int)value
{
    //nothing to do
}

- (BOOL) dataForChannelValid:(int)aChannel
{
    return [self isValid] && [serialPort isOpen];
}

- (void) recoverFromTimeout
{
    // Base class cleared the queue and set lastRequest=nil.
    // If we're still running, restart polling so we keep trying.
    if(running && [serialPort isOpen]){
        NSLog(@"PMS31(%d) Recovering from timeout, restarting polling.\n",[self uniqueIdNumber]);
        [dataBuffer setLength:0]; // clear stale data
        [self startPolling];
    }
}

@end

@implementation ORPMS31Model (private)

- (void) postCouchDBRecord
{    
    NSMutableArray* countsArray = [NSMutableArray arrayWithCapacity:kPMS31NumChannels];
    NSMutableArray* limitsArray = [NSMutableArray arrayWithCapacity:kPMS31NumChannels];
    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [countsArray addObject:[NSNumber numberWithInt:count[i]]];
        [limitsArray addObject:[NSNumber numberWithFloat:countAlarmLimit[i]]];
    }
    
    NSDictionary* values = [NSDictionary dictionaryWithObjectsAndKeys:
                            countsArray, @"counts",
                            limitsArray, @"countLimits",
                            [NSNumber numberWithInt:    cycleDuration],    @"pollTime",
                            nil];
    [[NSNotificationCenter defaultCenter] postNotificationName:@"ORCouchDBAddObjectRecord" object:self userInfo:values];
}

- (void) startPolling
{
    [self stopPolling];
    polling = YES;
    [self performSelector:@selector(pollOnce) withObject:nil afterDelay:pollInterval];
}

- (void) stopPolling
{
    polling = NO;
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollOnce) object:nil];
}

- (void) pollOnce
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollOnce) object:nil];
    if(polling && [serialPort isOpen]){
        [self readParticleCounts];
        [self performSelector:@selector(pollOnce) withObject:nil afterDelay:pollInterval];
    }
}

- (void) startCycleTimer
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(cycleComplete) object:nil];
    [self performSelector:@selector(cycleComplete) withObject:nil afterDelay:cycleDuration];
}

- (void) cancelCycleTimer
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(cycleComplete) object:nil];
}

- (void) cycleComplete
{
    NSLog(@"PMS31(%d) Cycle %d complete.\n",[self uniqueIdNumber], [self cycleNumber]);
    
    // Post the data record with current counts [add influxDB here]
    [self postCouchDBRecord];
    
    if(countingMode == kPMS31Auto){
        // Auto mode: increment cycle, clear counts, restart timers
        int theCount = [self cycleNumber];
        [self setCycleNumber:theCount+1];
        int i;
        for(i=0;i<kPMS31NumChannels;i++){
            [self setCount:i value:0];
        }
        [self setCycleStarted:[NSDate date]];
        [self startCycleTimer];
        [self startPolling];           // ensure polling is active
        [self startDataArrivalTimeout]; // reset safety net
        NSLog(@"PMS31(%d) Starting cycle %d\n",[self uniqueIdNumber],[self cycleNumber]);
    }
    else {
        // Manual/Single mode: stop after one cycle
        NSLog(@"PMS31(%d) Single cycle finished.\n",[self uniqueIdNumber]);
        [self stopCycle];
    }
}

- (void) startDataArrivalTimeout
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(doCycleKick) object:nil];
    [self performSelector:@selector(doCycleKick)  withObject:nil afterDelay:(cycleDuration+120)];
}

- (void) cancelDataArrivalTimeout
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(doCycleKick) object:nil];
}

- (void) doCycleKick
{
    [self setMissedCycleCount:missedCycleCount+1];
    NSLogColor([NSColor redColor],@"%@ data did not arrive at end of cycle (missed %d)\n",[self fullID],missedCycleCount);
    if(countingMode == kPMS31Auto){
        NSLogColor([NSColor redColor],@"Kickstarting %@\n",[self fullID]);
        int i;
        for(i=0;i<kPMS31NumChannels;i++){
            [self setCount:i value:0];
        }
        [self setIsValid:NO];
        [self stopCycle];
        [self startCycle:YES];
    }
}

- (void) addCmdToQueue:(NSData*)aCmd
{
    if([serialPort isOpen]){ 
        [self enqueueCmd:aCmd];
        if(!lastRequest){
            [self processOneCommandFromQueue];
        }
    }
    else NSLog(@"PMS31 (%d): Serial Port not open. Cmd Ignored.\n",[self uniqueIdNumber]);
}

- (void) processModbusResponse:(NSData*)responseData
{
    // We got a response, cancel the pending timeout and clear error state
    [self cancelTimeout];
    [self setTimeoutCount:0];
    
    unsigned char* bytes = (unsigned char*)[responseData bytes];
    int len = (int)[responseData length];
    
    // Validate CRC
    unsigned short receivedCRC = bytes[len-2] | (bytes[len-1] << 8);
    unsigned short calcCRC = [self modbusCalcCRC:bytes length:len-2];
    
    if(receivedCRC != calcCRC){
        NSLog(@"PMS31(%d): CRC mismatch in response. Expected 0x%04X, got 0x%04X\n",
              [self uniqueIdNumber], calcCRC, receivedCRC);
        [self setLastRequest:nil];
        [self processOneCommandFromQueue];
        return;
    }
    
    [self setIsValid:YES];
    
    unsigned char funcCode = bytes[1];
    
    // Check for error response
    if(funcCode & 0x80){
        unsigned char errCode = bytes[2];
        NSLog(@"PMS31(%d): Modbus error response. FC=0x%02X, Error=0x%02X\n",
              [self uniqueIdNumber], funcCode & 0x7F, errCode);
        [self setLastRequest:nil];
        [self processOneCommandFromQueue];
        return;
    }
    
    if(funcCode == kPMS31FC_ReadInputReg){
        // Parse particle count data
        // Response: [addr][0x04][byteCount][data...][crc_lo][crc_hi]
        int byteCount = bytes[2];
        if(byteCount == kPMS31Reg_CountsCount * 2){ // 28 bytes = 14 registers
            int i;
            for(i = 0; i < kPMS31NumChannels; i++){
                int offset = 3 + i * 4; // each channel = 2 registers = 4 bytes
                unsigned int hi = (bytes[offset] << 8) | bytes[offset+1];
                unsigned int lo = (bytes[offset+2] << 8) | bytes[offset+3];
                unsigned int countValue = (hi << 16) | lo;
                [self setCount:i value:(int)countValue];
            }
            
            // Update measurement date
            NSDateFormatter* dateFormatter = [[[NSDateFormatter alloc] init] autorelease];
            [dateFormatter setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
            NSString* dateStr = [dateFormatter stringFromDate:[NSDate date]];
            [self setMeasurementDate:dateStr];
            
            // Reset the data arrival safety timeout since we got good data
            [self setMissedCycleCount:0];
            [self cancelDataArrivalTimeout];
            [self startDataArrivalTimeout];
        }
    }
    else if(funcCode == kPMS31FC_WriteSingleReg){
        // Write single register echo — check if it was a start/stop command
        int regAddr = (bytes[2] << 8) | bytes[3];
        int regValue = (bytes[4] << 8) | bytes[5];
        if(regAddr == kPMS31Reg_StartStop){
            if(regValue == 0x0001){
                NSLog(@"PMS31(%d): Detection started\n",[self uniqueIdNumber]);
            }
            else if(regValue == 0x0000){
                NSLog(@"PMS31(%d): Detection stopped\n",[self uniqueIdNumber]);
            }
        }
    }
    else if(funcCode == kPMS31FC_WriteMultiReg){
        // Write multiple registers response — time sync confirmation
        NSLog(@"PMS31(%d): Time sync confirmed\n",[self uniqueIdNumber]);
    }
    
    [self setLastRequest:nil];
    [self processOneCommandFromQueue];
}

- (void) processOneCommandFromQueue
{
    NSData* cmdData = [self nextCmd];
    if(cmdData){
        [self startTimeout:kPMS31CmdTimeout];
        [self setLastRequest:cmdData];
        [serialPort writeDataInBackground:cmdData];
    }
}

@end
