//--------------------------------------------------------
// ORPMS31Controller
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

#import "ORPMS31Controller.h"
#import "ORPMS31Model.h"
#import "ORTimeLinePlot.h"
#import "ORCompositePlotView.h"
#import "ORTimeAxis.h"
#import "ORTimeRate.h"
#import "ORSerialPortController.h"
#import "ORSerialPort.h"

@implementation ORPMS31Controller

#pragma mark ***Initialization

- (id) init
{
    self = [super initWithWindowNibName:@"PMS31"];
    return self;
}

- (void) dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [blankView release];
    [super dealloc];
}

- (void) awakeFromNib
{
    [[plotter0 yAxis] setRngLow:0.0 withHigh:100.];
    [[plotter0 yAxis] setRngLimitsLow:0 withHigh:10000000. withMinRng:5];
    
    [[plotter0 xAxis] setRngLow:0.0 withHigh:10000];
    [[plotter0 xAxis] setRngLimitsLow:0.0 withHigh:200000. withMinRng:200];
    
    ORTimeLinePlot* aPlot = [[ORTimeLinePlot alloc] initWithTag:0 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor redColor]];
    [aPlot setName:@"0.3 \u00B5m"];
    [aPlot release];
    
    aPlot = [[ORTimeLinePlot alloc] initWithTag:1 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor greenColor]];
    [aPlot setName:@"0.5 \u00B5m"];
    [aPlot release];
    
    aPlot = [[ORTimeLinePlot alloc] initWithTag:2 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor blueColor]];
    [aPlot setName:@"0.7 \u00B5m"];
    [aPlot release];
    
    aPlot = [[ORTimeLinePlot alloc] initWithTag:3 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor blackColor]];
    [aPlot setName:@"1.0 \u00B5m"];
    [aPlot release];
    
    aPlot = [[ORTimeLinePlot alloc] initWithTag:4 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor cyanColor]];
    [aPlot setName:@"2.5 \u00B5m"];
    [aPlot release];
    
    aPlot = [[ORTimeLinePlot alloc] initWithTag:5 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor orangeColor]];
    [aPlot setName:@"5.0 \u00B5m"];
    [aPlot release];

    aPlot = [[ORTimeLinePlot alloc] initWithTag:6 andDataSource:self];
    [plotter0 addPlot: aPlot];
    [aPlot setLineColor:[NSColor brownColor]];
    [aPlot setName:@"10 \u00B5m"];
    [aPlot release];
    
    [plotter0 setShowLegend:YES];

    [(ORTimeAxis*)[plotter0 xAxis] setStartTime: [[NSDate date] timeIntervalSince1970]];

    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [[countAlarmLimitMatrix cellAtRow:i column:0] setTag:i];
        [[maxCountsMatrix cellAtRow:i column:0] setTag:i];
    }
    
    blankView = [[NSView alloc] init];
    basicOpsSize    = NSMakeSize(422,528);
    processOpsSize  = NSMakeSize(385,370);
    historyOpsSize  = NSMakeSize(422,480);
    summaryOpsSize  = NSMakeSize(400,270);
    
    NSString* key = [NSString stringWithFormat: @"orca.ORPMS31%u.selectedtab",[model uniqueIdNumber]];
    NSInteger index = [[NSUserDefaults standardUserDefaults] integerForKey: key];
    if((index<0) || (index>[tabView numberOfTabViewItems]))index = 0;
    [tabView selectTabViewItemAtIndex: index];
    
    NSUInteger style = [[self window] styleMask];
    if(index == 2){
        [[self window] setStyleMask: style | NSWindowStyleMaskResizable];
    }
    else {
        [[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
    }
    
    [super awakeFromNib];
}

- (void) setModel:(id)aModel
{
    [super setModel:aModel];
    [[self window] setTitle:[NSString stringWithFormat:@"PMS31 (Unit %u)",[model uniqueIdNumber]]];
}

- (BOOL) portLocked
{
    return [gSecurity isLocked:ORPMS31Lock];;
}

#pragma mark ***Notifications

- (void) registerNotificationObservers
{
    NSNotificationCenter* notifyCenter = [NSNotificationCenter defaultCenter];
    [super registerNotificationObservers];
    [notifyCenter addObserver : self
                     selector : @selector(lockChanged:)
                         name : ORRunStatusChangedNotification
                       object : nil];
    
    [notifyCenter addObserver : self
                     selector : @selector(lockChanged:)
                         name : ORPMS31Lock
                        object: nil];

    [notifyCenter addObserver : self
                     selector : @selector(measurementDateChanged:)
                         name : ORPMS31ModelMeasurementDateChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(countChanged:)
                         name : ORPMS31ModelCountChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(countingModeChanged:)
                         name : ORPMS31ModelCountingModeChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleDurationChanged:)
                         name : ORPMS31ModelCycleDurationChanged
                        object: model];
    [notifyCenter addObserver : self
                     selector : @selector(holdDurationChanged:)
                         name : ORPMS31ModelHoldDurationChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(runningChanged:)
                         name : ORPMS31ModelRunningChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleStartedChanged:)
                         name : ORPMS31ModelCycleStartedChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleWillEndChanged:)
                         name : ORPMS31ModelCycleWillEndChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(cycleNumberChanged:)
                         name : ORPMS31ModelCycleNumberChanged
                        object: model];

    [notifyCenter addObserver : self
                      selector : @selector(scaleAction:)
                          name : ORAxisRangeChangedNotification
                        object : nil];
    
    [notifyCenter addObserver : self
                      selector : @selector(miscAttributesChanged:)
                          name : ORMiscAttributesChanged
                        object : model];
    
    [notifyCenter addObserver : self
                      selector : @selector(updateTimePlot:)
                          name : ORRateAverageChangedNotification
                        object : nil];
    
    [notifyCenter addObserver : self
                     selector : @selector(maxCountsChanged:)
                         name : ORPMS31ModelMaxCountsChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(countAlarmLimitChanged:)
                         name : ORPMS31ModelCountAlarmLimitChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(isLogChanged:)
                         name : ORPMS31ModelIsLogChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(timedOutChanged:)
                         name : ORSerialPortWithQueueModelTimeoutCountChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(slaveAddressChanged:)
                         name : ORPMS31ModelSlaveAddressChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(baudRateChanged:)
                         name : ORPMS31ModelBaudRateChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(pollIntervalChanged:)
                         name : ORPMS31ModelPollIntervalChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(deviceCountModeChanged:)
                         name : ORPMS31ModelDeviceCountModeChanged
                        object: model];
    
    [notifyCenter addObserver : self
                     selector : @selector(deviceSampleUnitModeChanged:)
                         name : ORPMS31ModelDeviceSampleUnitChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(serialNumberChanged:)
                         name : ORPMS31ModelSerialNumberChanged
                        object: model];

    [notifyCenter addObserver : self
                     selector : @selector(portStateChanged:)
                         name : ORSerialPortModelPortStateChanged
                        object: model];
    
    [serialPortController registerNotificationObservers];
}

- (void) updateWindow
{
    [super updateWindow];
    [self lockChanged:nil];
    [self measurementDateChanged:nil];
    [self countChanged:nil];
    [self countingModeChanged:nil];
    [self cycleDurationChanged:nil];
    [self holdDurationChanged:nil];
    [self runningChanged:nil];
    [self cycleStartedChanged:nil];
    [self cycleWillEndChanged:nil];
    [self cycleNumberChanged:nil];
    [self updateTimePlot:nil];
    [self miscAttributesChanged:nil];
    [self maxCountsChanged:nil];
    [self countAlarmLimitChanged:nil];
    [self isLogChanged:nil];
    [self timedOutChanged:nil];
    [self slaveAddressChanged:nil];
    [self baudRateChanged:nil];
    [self pollIntervalChanged:nil];
    [self deviceCountModeChanged:nil];
    [self deviceCountModeChanged:nil];
    [self serialNumberChanged:nil];
    [serialPortController updateWindow];
}

- (void) timedOutChanged:(NSNotification*)aNote
{
    [timedOutField setStringValue: [model timeoutCount]!=0 ? @"Last Command Timed Out":@""];
}

- (void) serialNumberChanged:(NSNotification*)aNote
{
    [serialNumberField setStringValue:[model serialNumber]];
}

- (void) portStateChanged:(NSNotification*)aNote
{
    [self updateButtons];
}

- (void) isLogChanged:(NSNotification*)aNote
{
    [isLogCB setIntValue: [model isLog]];
    [[plotter0 yAxis] setLog:[model isLog]];
    [plotter0 setNeedsDisplay:YES];
}

- (void) slaveAddressChanged:(NSNotification*)aNote
{
    [slaveAddressField setIntegerValue: [model slaveAddress]];
}

- (void) baudRateChanged:(NSNotification*)aNote
{
    int baud = [model baudRate];
    if(baud == 9600)       [baudRatePU selectItemAtIndex:0];
    else if(baud == 19200) [baudRatePU selectItemAtIndex:1];
    else if(baud == 115200)[baudRatePU selectItemAtIndex:2];
}

- (void) pollIntervalChanged:(NSNotification*)aNote
{
    [pollIntervalField setIntegerValue: [model pollInterval]];
}

- (void) deviceCountModeChanged:(NSNotification*)aNote
{
    [deviceCountModePU selectItemAtIndex: [model deviceCountMode]];
}

- (void) deviceSampleUnitModeChanged:(NSNotification *)aNote
{
    [deviceSampleUnitModePU selectItemAtIndex:[model deviceSampleUnit]];
}
- (void) countAlarmLimitChanged:(NSNotification*)aNote
{
    if(!aNote){
        int i;
        for(i=0;i<kPMS31NumChannels;i++){
            [[countAlarmLimitMatrix cellWithTag:i] setStringValue:[NSString stringWithFormat:@"%d",(int)[model countAlarmLimit:i]]];
        }
    }
    else {
        int chan = [[[aNote userInfo] objectForKey:@"Channel"] intValue];
        if(chan<kPMS31NumChannels){
            [[countAlarmLimitMatrix cellWithTag:chan] setStringValue:[NSString stringWithFormat:@"%d",(int)[model countAlarmLimit:chan]]];
        }
    }
}

- (void) maxCountsChanged:(NSNotification*)aNote
{
    if(!aNote){
        int i;
        for(i=0;i<kPMS31NumChannels;i++){
            [[maxCountsMatrix cellWithTag:i] setStringValue:[NSString stringWithFormat:@"%d",(int)[model maxCounts:i]]];
        }
    }
    else {
        int chan = [[[aNote userInfo] objectForKey:@"Channel"] intValue];
        if(chan<kPMS31NumChannels){
            [[maxCountsMatrix cellWithTag:chan] setStringValue:[NSString stringWithFormat:@"%d",(int)[model maxCounts:chan]]];
        }
    }
}

- (void) scaleAction:(NSNotification*)aNotification
{
    if(aNotification == nil || [aNotification object] == [plotter0 xAxis]){
        [model setMiscAttributes:[(ORAxis*)[plotter0 xAxis]attributes] forKey:@"XAttributes0"];
    };
    
    if(aNotification == nil || [aNotification object] == [plotter0 yAxis]){
        [model setMiscAttributes:[(ORAxis*)[plotter0 yAxis]attributes] forKey:@"YAttributes0"];
    };
}

- (void) miscAttributesChanged:(NSNotification*)aNote
{
    NSString*               key = [[aNote userInfo] objectForKey:ORMiscAttributeKey];
    NSMutableDictionary* attrib = [model miscAttributesForKey:key];
    
    if(aNote == nil || [key isEqualToString:@"XAttributes0"]){
        if(aNote==nil)attrib = [model miscAttributesForKey:@"XAttributes0"];
        if(attrib){
            [(ORAxis*)[plotter0 xAxis] setAttributes:attrib];
            [plotter0 setNeedsDisplay:YES];
            [[plotter0 xAxis] setNeedsDisplay:YES];
        }
    }
    if(aNote == nil || [key isEqualToString:@"YAttributes0"]){
        if(aNote==nil)attrib = [model miscAttributesForKey:@"YAttributes0"];
        if(attrib){
            [(ORAxis*)[plotter0 yAxis] setAttributes:attrib];
            [plotter0 setNeedsDisplay:YES];
            [[plotter0 yAxis] setNeedsDisplay:YES];
        }
    }
}

- (void) updateTimePlot:(NSNotification*)aNote
{
    if(!aNote || ([aNote object] == [model timeRate:0])){
        [plotter0 setNeedsDisplay:YES];
    }
}

- (void) cycleStartedChanged:(NSNotification*)aNote
{    
    NSDateFormatter* dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
    NSString* startDateString = [dateFormatter stringFromDate:[model cycleStarted]];
    [dateFormatter release];
    if(startDateString && [model running]) [cycleStartedField setStringValue:startDateString];
    else [cycleStartedField setStringValue:@"---"];
}

- (void) cycleWillEndChanged:(NSNotification*)aNote
{
    NSDateFormatter* dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
    NSString* endDateString = [dateFormatter stringFromDate:[model cycleWillEnd]];
    [dateFormatter release];
    NSString* s;
    if(endDateString && [model running]) {
        if([model countingMode] == kPMS31Manual) s = @"--";
        else s = endDateString;
    }
    else s = @"---";
    [cycleWillEndField setStringValue:s];
    [cycleWillEnd2Field setStringValue:s];
}

- (void) cycleNumberChanged:(NSNotification*)aNote
{
    [cycleNumberField setIntValue: [model cycleNumber]];
}

- (void) runningChanged:(NSNotification*)aNote
{
    [self updateButtons];
    [runningField setStringValue:[model running]?@"Counting":@"Idle"];
    [running2Field setStringValue:[model running]?@"Counting":@"Idle"];
    [self cycleStartedChanged:nil];
    [self cycleWillEndChanged:nil];
}

- (void) cycleDurationChanged:(NSNotification*)aNote
{
    [cycleDurationField setIntValue: [model cycleDuration]];
}

- (void) holdDurationChanged:(NSNotification *)aNote
{
    [holdDurationField setIntValue:[model holdDuration]];
}

- (void) countingModeChanged:(NSNotification*)aNote
{
    [countingModePU selectItemAtIndex: [model countingMode]];
    [self updateButtons];
}

- (void) countChanged:(NSNotification*)aNote
{
    int i;
    for(i=0;i<kPMS31NumChannels;i++){
        [[countMatrix cellAtRow:i column:0] setIntValue:[model count:i]];
        [[count2Matrix cellAtRow:i column:0] setIntValue:[model count:i]];
    }
}

- (void) measurementDateChanged:(NSNotification*)aNote
{
    [measurementDateField setStringValue: [model measurementDate]];
    [measurementDate2Field setStringValue: [model measurementDate]];
}

- (void) checkGlobalSecurity
{
    BOOL secure = [[[NSUserDefaults standardUserDefaults] objectForKey:OROrcaSecurityEnabled] boolValue];
    [gSecurity setLock:ORPMS31Lock to:secure];
    [lockButton setEnabled:secure];
}

- (void) lockChanged:(NSNotification*)aNotification
{
    [self updateButtons];
}

- (void) updateButtons
{
    BOOL locked    = [gSecurity isLocked:ORPMS31Lock];
    BOOL portOpen  = [[model serialPort] isOpen];
    BOOL isRunning = [model running];
    
    [serialPortController updateButtons:locked];

    [lockButton setState: locked];
    
    if(!locked && portOpen){
        [startCycleButton setEnabled:!isRunning];
        [stopCycleButton setEnabled:isRunning];
    }
    else {
        [startCycleButton setEnabled:NO];
        [stopCycleButton setEnabled:NO];
    }
    BOOL canEdit = !isRunning && !locked;
    [cycleDurationField setEnabled:canEdit];
    [holdDurationField setEnabled:canEdit];
    [countingModePU setEnabled:canEdit];
    [slaveAddressField setEnabled:canEdit && !portOpen];
    [baudRatePU setEnabled:canEdit && !portOpen];
    [pollIntervalField setEnabled:canEdit];
    [deviceCountModePU setEnabled:canEdit];
    [deviceSampleUnitModePU setEnabled:canEdit];
    [syncButton setEnabled:portOpen && !locked && !isRunning];
    [writeSettingsButton setEnabled:portOpen && !locked && !isRunning];
}

- (void)tabView:(NSTabView *)aTabView didSelectTabViewItem:(NSTabViewItem *)tabViewItem
{
    [[self window] setContentView:blankView];
    NSUInteger style = [[self window] styleMask];
    switch([tabView indexOfTabViewItem:tabViewItem]){
        case  0: 
            [self resizeWindowToSize:basicOpsSize];   
            [[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
            break;
        case  1: 
            [self resizeWindowToSize:processOpsSize];     
            [[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
            break;
        case  2: 
            [self resizeWindowToSize:historyOpsSize];    
            [[self window] setStyleMask: style | NSWindowStyleMaskResizable];
            break;
        default: 
            [self resizeWindowToSize:summaryOpsSize];     
            [[self window] setStyleMask: style & ~NSWindowStyleMaskResizable];
            break;
    }
    [[self window] setContentView:totalView];
    
    NSString* key = [NSString stringWithFormat: @"orca.ORPMS31%u.selectedtab",[model uniqueIdNumber]];
    NSInteger index = [tabView indexOfTabViewItem:tabViewItem];
    [[NSUserDefaults standardUserDefaults] setInteger:index forKey:key];
}

- (void)windowDidResize:(NSNotification *)notification
{
    if([tabView indexOfTabViewItem:[tabView selectedTabViewItem]] == 2){
        historyOpsSize = [[self window] frame].size; 
    }
}

#pragma mark ***Actions

- (IBAction) isLogAction:(id)sender
{
    [model setIsLog:[sender intValue]];    
}

- (IBAction) slaveAddressAction:(id)sender
{
    [model setSlaveAddress:[sender intValue]];
}

- (IBAction) baudRateAction:(id)sender
{
    int index = (int)[sender indexOfSelectedItem];
    int baud = 9600;
    if(index == 1) baud = 19200;
    else if(index == 2) baud = 115200;
    [model setBaudRate:baud];
}

- (IBAction) pollIntervalAction:(id)sender
{
    [model setPollInterval:[sender intValue]];
}

- (IBAction) deviceCountModeAction:(id)sender
{
    [model setDeviceCountMode:(int)[sender indexOfSelectedItem]];
}

- (IBAction) deviceSampleUnitModeAction:(id)sender
{
    [model setDeviceSampleUnit:(int)[sender indexOfSelectedItem]];
}
- (IBAction) countingModeAction:(id)sender
{
    [model setCountingMode:(int)[sender indexOfSelectedItem]];
}
- (IBAction) probePMS31Hardware:(id)sender
{
    [model probeDevice];
}
- (IBAction) syncSettingsAction:(id)sender
{
    [model readDeviceSettings];
    [model readSerialNumber];
}

- (IBAction) writeSettingsAction:(id)sender
{
    [model writeSettingsToDevice];
}
- (IBAction) countAlarmLimitAction:(id)sender
{
    NSString* raw = [[[sender selectedCell] stringValue] stringByReplacingOccurrencesOfString:@" " withString:@""];
    [model setIndex:(int)[[sender selectedCell] tag] countAlarmLimit:(float)[raw intValue]];    
}

- (IBAction) maxCountsAction:(id)sender
{
    NSString* raw = [[[sender selectedCell] stringValue] stringByReplacingOccurrencesOfString:@" " withString:@""];
    [model setIndex:(int)[[sender selectedCell] tag] maxCounts:(float)[raw intValue]];
}

- (IBAction) startCycleAction:(id)sender
{
    [self endEditing];
    [model setMissedCycleCount:0];
    [model startCycle];    
}

- (IBAction) stopCycleAction:(id)sender
{
    [self endEditing];
    [model setMissedCycleCount:0];
    [model stopCycle];    
}

- (IBAction) cycleDurationAction:(id)sender
{
    [model setCycleDuration:[sender intValue]];    
}

- (IBAction)holdDurationAction:(id)sender
{
    [model setHoldDuration:[sender intValue]];
}

- (IBAction) lockAction:(id) sender
{
    [gSecurity tryToSetLock:ORPMS31Lock to:[sender intValue] forWindow:[self window]];
}

#pragma mark •••Data Source
- (int) numberPointsInPlot:(id)aPlotter
{
    return (int)[[model timeRate:(int)[aPlotter tag]]   count];
}

- (void) plotter:(id)aPlotter index:(int)i x:(double*)xValue y:(double*)yValue
{
    int set = (int)[aPlotter tag];
    int count = (int)[[model timeRate:set] count];
    int index = count-i-1;
    *yValue = [[model timeRate:set] valueAtIndex:index];
    *xValue = [[model timeRate:set] timeSampledAtIndex:index];
}

@end
