//--------------------------------------------------------
// ORPMS31Model
// Created by Mark  A. Howe on Mon Jan 23, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files
#import "ORAdcProcessing.h"
#import "ORSerialPortWithQueueModel.h"

@class ORTimeRate;
@class ORAlarm;

// PMS31 Timing Constants
#define kPMS31CmdTimeout          5
#define kPMS31DefaultPollInterval 5
#define kPMS31NumChannels         7

// Modbus Defaults
#define kPMS31DefaultSlaveAddr    0xFE
#define kPMS31DefaultBaudRate     9600

// Modbus Function Codes
#define kPMS31FC_ReadHoldingReg   0x03
#define kPMS31FC_ReadInputReg     0x04
#define kPMS31FC_WriteSingleReg   0x06
#define kPMS31FC_WriteMultiReg    0x10

// Modbus Register Addresses
#define kPMS31Reg_SlaveAddr       0x0000
#define kPMS31Reg_StartStop       0x0001
#define kPMS31Reg_CountsStart     0x0003
#define kPMS31Reg_CountsCount     0x000E  // 14 registers (7 channels x 2)
#define kPMS31Reg_TimeStart       0x0008
#define kPMS31Reg_TimeCount       0x0006  // 6 registers (yr,mo,dy,hr,mn,sc)
#define kPMS31Reg_CountMode       0x000E  // 0x00=Sum(cumulative), 0x01=Diff(differential)
#define kPMS31Reg_SampleUnit      0x000F
#define kPMS31Reg_SampleTime      0x0010  // Sample/cycle duration time
#define kPMS31Reg_HoldTime        0x0011  // Hold/delay time between sampling cycles

// Serial Number Registers (6 registers, each holds one character/value)
#define kPMS31Reg_SerialStart     0x0020  // Serial Number 0
#define kPMS31Reg_SerialCount     6       // 6 registers (0x20-0x25)
// ORCA Cycle Modes
#define kPMS31Manual  0
#define kPMS31Auto    1
//add the sampling unit mode
#define kPMS31SampleUnitTC 0
#define kPMS31SampleUnitCF 1
#define kPMS31SampleUnitL  2
#define kPMS31SampleUnitM3 0
// Device Count Modes
#define kPMS31CountModeSum   0
#define kPMS31CountModeDiff  1

@interface ORPMS31Model : ORSerialPortWithQueueModel <ORAdcProcessing>
{
    @private
        NSMutableData*  dataBuffer;
        NSString*       measurementDate;
        ORTimeRate*     timeRates[kPMS31NumChannels];
        int             count[kPMS31NumChannels];
        float           maxCounts[kPMS31NumChannels];
        float           countAlarmLimit[kPMS31NumChannels];
        int             countingMode;
        int             cycleDuration;
        int             holdDuration;
        BOOL            running;
        NSDate*         cycleStarted;
        NSDate*         cycleWillEnd;
        int             cycleNumber;
        BOOL            wasRunning;
        int             location;
        BOOL            isLog;
        int             slaveAddress;
        int             baudRate;
        int             pollInterval;
        int             deviceCountMode;
        int             deviceSampleUnit;
        BOOL            polling;
        ORAlarm*        missingCyclesAlarm;
        BOOL            sentStartOnce;
        BOOL            sentStopOnce;
        int             missedCycleCount;
        int             expectedResponseLength;
        NSString*       serialNumber;
}


#pragma mark ***Initialization
- (id)   init;
- (void) dealloc;
- (void) dataReceived:(NSNotification*)note;

#pragma mark ***Accessors
- (int) slaveAddress;
- (void) setSlaveAddress:(int)aSlaveAddress;
- (int) baudRate;
- (void) setBaudRate:(int)aBaudRate;
- (int) pollInterval;
- (void) setPollInterval:(int)aPollInterval;
- (int) deviceCountMode;
- (void) setDeviceCountMode:(int)aMode;
- (int) deviceSampleUnit;
- (void) setDeviceSampleUnit:(int)aUnit;
- (BOOL) isLog;
- (void) setIsLog:(BOOL)aIsLog;
- (int) location;
- (void) setLocation:(int)aLocation;
- (ORTimeRate*)timeRate:(int)index;
- (int) cycleNumber;
- (void) setCycleNumber:(int)aCycleNumber;
- (NSDate*) cycleWillEnd;
- (void) setCycleWillEnd:(NSDate*)aCycleWillEnd;
- (NSDate*) cycleStarted;
- (void) setCycleStarted:(NSDate*)aCycleStarted;
- (BOOL) running;
- (void) setRunning:(BOOL)aRunning;
- (int) cycleDuration;
- (int) holdDuration;
- (void) setCycleDuration:(int)aCycleDuration;
- (void) setHoldDuration:(int)aHoldDuration;
- (int) countingMode;
- (void) setCountingMode:(int)aCountingMode;
- (void) setCount:(int)index value:(int)aValue;
- (int) count:(int)index;
- (NSString*) measurementDate;
- (void) setMeasurementDate:(NSString*)aMeasurementDate;
- (NSString*) countingModeString;
- (float) countAlarmLimit:(int)index;
- (void) setIndex:(int)index countAlarmLimit:(float)aCountAlarmLimit;
- (float) maxCounts:(int)index;
- (void) setIndex:(int)index maxCounts:(float)aMaxCounts;
- (void) setMissedCycleCount:(int)aValue;
- (int) missedCycleCount;
- (NSString*) serialNumber;
- (void) setSerialNumber:(NSString*)aSerialNumber;

#pragma mark ***Polling
- (void) startCycle:(BOOL)force;
- (void) startCycle;
- (void) stopCycle;

#pragma mark ***Modbus Commands
- (void) readParticleCounts;
- (void) startDetection;
- (void) stopDetection;
- (void) syncDeviceTime;
- (void) sendDeviceCountMode;
- (void) sendDeviceUnitMode;
- (void) sendCycleDuration;
- (void) sendHoldDuration;
- (void) readSerialNumber;

#pragma mark ***Modbus Helpers
- (unsigned int) modbusCalcCRC:(unsigned char*)data length:(int)length;
- (NSData*) buildReadInputRegistersFrame:(int)startReg count:(int)regCount;
- (NSData*) buildReadHoldingRegistersFrame:(int)startReg count:(int)regCount;
- (NSData*) buildWriteSingleRegisterFrame:(int)reg value:(int)value;
- (NSData*) buildWriteMultipleRegistersFrame:(int)startReg values:(int*)values count:(int)regCount;

#pragma mark •••Adc Processing Protocol
- (void)processIsStarting;
- (void)processIsStopping;
- (void) startProcessCycle;
- (void) endProcessCycle;
- (BOOL) processValue:(int)channel;
- (void) setProcessOutput:(int)channel value:(int)value;
- (NSString*) processingTitle;
- (void) getAlarmRangeLow:(double*)theLowLimit high:(double*)theHighLimit  channel:(int)channel;
- (double) convertedValue:(int)channel;
- (double) maxValueForChan:(int)channel;
- (BOOL) dataForChannelValid:(int)aChannel;

#pragma mark •••Archival
- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;

@end

extern NSString* ORPMS31ModelIsLogChanged;
extern NSString* ORPMS31ModelLocationChanged;
extern NSString* ORPMS31ModelCountAlarmLimitChanged;
extern NSString* ORPMS31ModelMaxCountsChanged;
extern NSString* ORPMS31ModelCycleNumberChanged;
extern NSString* ORPMS31ModelCycleWillEndChanged;
extern NSString* ORPMS31ModelCycleStartedChanged;
extern NSString* ORPMS31ModelRunningChanged;
extern NSString* ORPMS31ModelCycleDurationChanged;
extern NSString* ORPMS31ModelHoldDurationChanged;
extern NSString* ORPMS31ModelCountingModeChanged;
extern NSString* ORPMS31ModelCountChanged;
extern NSString* ORPMS31ModelMeasurementDateChanged;
extern NSString* ORPMS31ModelMissedCountChanged;
extern NSString* ORPMS31ModelSlaveAddressChanged;
extern NSString* ORPMS31ModelBaudRateChanged;
extern NSString* ORPMS31ModelPollIntervalChanged;
extern NSString* ORPMS31ModelDeviceCountModeChanged;
extern NSString* ORPMS31ModelDeviceSampleUnitChanged;
extern NSString* ORPMS31ModelSerialNumberChanged;

extern NSString* ORPMS31Lock;
